### ISSUE TITLE
Documentation needed for the tridentctl 'macos' binary,

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#10]
Please add some documentation for the tridentctl 'macos' binary, (not mentioned anywhere in Trident doc pages). 

Suggested minimal documentation needed is below:

.............................................

Below is the path/location for the macos tridentctl, 
https://docs.netapp.com/us-en/trident/?q=macos)

# /trident-installer/extras/macos/bin
[root@rhel3 bin]# ls -lia
202861080 -rwxr-xr-x 1 root root 54263072 Sep 22 2020 tridentctl

............................................

-> Please add any further helpful information regarding the use of macos option.

**Comment by netapp-amitha** [comment]
@crossond thanks for pointing this out. I'll update the documentation after doing some research about this. I created this Jira ticket to track efforts: https://jira.ngage.netapp.com/browse/DOC-3802

**Comment by netapp-amitha** [comment]
@crossond I learned that the macos binary works in the same way tridentctl. It is not tested/supported, but it works in the same way. Is there anything specific that you are looking for that I can document?

**Comment by netapp-amitha** [comment]
Sounds good @crossond . I will update the docs. Thanks.
