### ISSUE TITLE
Typos need correction

### ISSUE THREAD

**Issue by pnanto** [NetAppDocs/trident#109]
Page: [Upgrade with the operator](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html)

In this paragraph:
(Optional) If you want to modify the installation parameters, edit the TridentOrchestrator object that you crated when installing Trident.
These could be changes, such as modifying the custom Trident image, private image registry to pull container images from, enabling debug logs, or specifying image pull secrets.

First sentence: "crated" is a typo and should be "created"
Second sentence: "These" I think needs to be "There"?

**Comment by juliantap** [comment]
Hi @pnanto, thank you for the feedback! Good catch on "crated". I've fixed that. For the second issue, "these" was actually correct. It's intended to mean that the changes can include any of the following scenarios. I've tweaked it to:

> This can include changes, such as modifying the custom Trident image, private image registry to pull container images from, enabling debug logs, ...

I hope this helps! And thanks again for your review and feedback!
