### ISSUE TITLE
22.04.0 Requirements Update

### ISSUE THREAD

**Issue by gnarl** [NetAppDocs/trident#130]
Page: [Requirements](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html)

Update Kubernetes 1.17 -> Kubernetes 1.18 in multiple places. “Feature requirements” table does NOT get updated though.

Update OpenShift 4.7, 4.8, 4.9 -> OpenShift 4.7, 4.8, 4.9, 4.10 in two places in Supported Frontends

Update "Container images and corresponding Kubernetes versions"
+--------------------+---------------------------------------------------------+
| KUBERNETES VERSION |                     CONTAINER IMAGE                     |
+--------------------+---------------------------------------------------------+
| v1.17.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+
| v1.18.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+
| v1.19.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+
| v1.20.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+
| v1.21.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+
| v1.22.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+
| v1.23.0            | netapp/trident:22.04.0-custom                           |
|                    | netapp/trident-autosupport:22.04                        |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.4.0              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.4.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0 |
|                    | netapp/trident-operator:22.04.0-custom (optional)       |
+--------------------+---------------------------------------------------------+

**Comment by juliantap** [comment]
@gnarl req updates are in: https://github.com/NetAppDocs/trident-internal/pull/71
