### ISSUE TITLE
Specific links to current version should be created on release

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/trident#135]
Current page [Earlier versions of documentation](https://docs.netapp.com/us-en/trident/earlier-versions.html) doesn't have a link to 22.04 documentation - [https://docs.netapp.com/us-en/trident-2204/index.html](https://docs.netapp.com/us-en/trident-2204/index.html) is 404.

That makes it impossible to link to specific version of the documentation if that version happens to be the current version.

**Comment by juliantap** [comment]
Hi @scaleoutsean, thanks for the feedback.

The current version of the docs is always us-en/trident/ (with no version number). If you think it's helpful, I could go back a few versions and add a static link to "latest version" and it would be in all upcoming versions. However, it might be a bit confusing to have a link to the latest version in the latest version.

**Comment by scaleoutsean** [comment]
The old doco site for Trident had the latest version called out by version so this behavior is new.

The usability problem with the new approach is we can't create links to specific pages that will be valid 4 months from now.

I'll let others chime in if they are interested in this topic.

**Comment by juliantap** [comment]
Thank you for the additional use case. We are experimenting with adding a version selector and that might help. However, I don't believe we would consider changing the overall naming structure as most customers will want to navigate the the latest version, without necessarily having to know the version number.

**Comment by scaleoutsean** [comment]
Thank you. 

For reference, I mentioned the old site offered the possibility to get permalinks for current release by navigating its tag (rather than `latest`):

![image](https://user-images.githubusercontent.com/16622642/166862110-963b9ee2-3065-4b4b-a42c-319b23745a47.png)

**Comment by juliantap** [comment]
Hi @scaleoutsean, in the current structure, the base `trident` repo will always take you to the latest version (major or patch release). So, you can use those as the permalink. 

For example:

- https://docs.netapp.com/us-en/**trident**/trident-concepts/intro.html always links to the Intro for the latest release. Bookmarking this URL or navigating from [docs.netapp.com ](https://docs.netapp.com/) gets you to the current release. 
- You can append a previous release number into the URL to get to any earlier release. For example https://docs.netapp.com/us-en/trident-2110/trident-concepts/intro.html will take you to Intro for 21.10.
- Or you can use the Earlier Versions page to get to earlier ones. Or (when I get the drop-down finalized) you'll be able to navigate from current to past and back again using the selector. 

So you don't need to use `latest` or a future release number to get to the latest and greatest.

**Comment by scaleoutsean** [comment]
> in the current structure, the base trident repo will always take you to the latest version (major or patch release).

Yes, that's one of the problems that I'd like to see fixed. Maybe the earlier examples weren't clear so I'll try again:

Let's say today I start working on planning for a cluster that will use Trident v22.04. I have no "hard" v22.04 links at this time, so I must use `latest`. 

Then this time in August v22.07 becomes the new `latest` and all the old `latest` links I prepared may or may not be valid (so may become 404) or correct (some details may change in v22.07). 

Now I have a problem. And as I mentioned elsewhere, because documentation commits are sparse ("push 912fad to Github") I can't even tell which of my links may now link to `latest` that contains advice or steps accurate for v22.07 but inaccurate for v22.04.

**Comment by juliantap** [comment]
Hi @scaleoutsean, as this is a structural, versus content, issue, I'm going to close this and pick up the conversation using email.
