### ISSUE TITLE
Update snapshot CRDs and controller

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#136]
Page: [Work with snapshots](https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html)

In the section "What you’ll need", the docs point to outdated versions on the snapshot CRDs and snapshot controller. Could we please modify this, so it differentiates by K8s version ("1.17-1.19" and "1.20 and higher") and then provides the links for the latest versions of the CRDs and Controller?

I'm proposing the following:

You can create an external snapshot-controller and snapshot CRDs as follows:

Create volume snapshot CRDs:

For Kubernetes 1.20 and above use v1:

kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.1.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.1.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.1.1/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

For Kubernetes versions 1.17-1.19 use v1beta1:

kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

Create the snapshot-controller in the desired namespace. Edit the YAML manifests below to modify namespace.

For Kubernetes 1.20 and above use v4.1.1:

kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.1.1/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v4.1.1/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

For Kubernetes versions 1.17-1.19 use v3.0.3

kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/v3.0.3/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

**Comment by clintonk** [comment]
I agree we should make this specific to the Kubernetes version.  The links are correct for K8s 1.17-1.19, but for K8s 1.20+, we should be pointing to the v5 content (will be v6 soon).

v5 CRDs:
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml

Controller (comment about editing the YAML to change the namespace still applies):
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/release-5.0/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml

**Comment by juliantap** [comment]
Thanks, @clintonk! I'm on it!

**Comment by juliantap** [comment]
Thanks again @wonderland! This has been fixed.
