### ISSUE TITLE
 alter the documentation when Implementing

### ISSUE THREAD

**Issue by eone74** [NetAppDocs/trident#144]
Page: [Astra Trident 22.04 documentation](https://docs.netapp.com/us-en/trident/index.html)

Kind request to you to alter the documentation when Implementing based on the error messages one of my customer had.

**_1. iSCSI nodes_**

aggregate  error message                                                                         
<aggr> have no LIFs configured with the iSCSI  correct. 
The node <node> has no LIFs configured with the iSCSI  not correct: service-policy

This first issue has been resolved.
What the error reflects is that trident NEEDS two iscsi lifs to communicate with the NetApp. Since the first node did not provide two iscsi LIFS, Trident started asking the other nodes if they had any available lifs. Hence the node errors during the configuration of K8s.

Although I understand that two ISCSI LIFS are recommended from a data availability point of view, there is no mention that this is a REQUIREMENT in the documentation of Trident.
I was unable to find this requirement in the documentation of Trident, so I would kindly request to you to **alter the documentation of Trident and make a notion of the fact that two ISCSI LIFS are required when configuring trident for block storage.**

**_2.  service-policy vs data-protocol_**

The second issue is also resolved:
Creating a LIF with the service-policy: default-data-blocks does not allow Trident to use this LIF.
However if we create a lif with the -obsolete- command -data-protocol ISCSI Trident does recognize the LIFS as being block data provided.

Here we also found the solution:
The default-data-blocks service-policy contains the 'Service: Allowed Addresses' part:: data-core: 0.0.0.0/0 making this policy only available for FCP. If ISCSI is needed the value "data-iscsi: 0.0.0.0/0" has to be added to the 'Service: Allowed Addresses' (or of cause a new policy has to be created.

In our opinion the service policy "default-data-blocks" is not configured correctly in the default NetApp Ontap.
If I specify a default-data-blocks policy I expect the LIF to carry data blocks protocols. Both ISCSI and FCP.
The same goes for the "default-data-files" service policy. Here only NFS is configured while the last time I checked CIFS also was considered a data-file option.
**I would suggest a rename of the policy, or the addition of the protocols.**

**Comment by juliantap** [comment]
Hi @eone74, thank you for the feedback!

@balaramesh and @gnarl can you provide some guidance on how we should resolve this request?

**Comment by gnarl** [comment]
@eone74, from what I can tell from this description there isn't anything required here from the Trident side. The error message indicates that no dataLIFs were configured to support iSCSI. If there aren't any iSCSI dataLIFs configured then Trident doesn't have a path to attach the volume.

For the second issue this doesn't sound correct. Trident makes use of the iSCSI service available on the K8S host and doesn't care how the service-policy on the SVM is configured. As far as Trident is concerned, if ONTAP is configured correctly then the volume attachment will just work.

**Comment by eone74** [comment]
Hi Chuck,

My name is Iwan Engelberts from PROACT The Netherlands and I'm hoping to 'help' other NetApp customers so the Installation/Configuration documentation is 100% correct.
It looks like the Trident docs have now collapsed into docs.netapp.com link below so NetApp customers rely on what the Trident docs are providing. Maybe this is not the way to go.
Do you think NetApp (docs) should be placing some extra information to have the K8S host connected correctly?
I understand you don't want to publish specific NetApp information on the Trident docs.


https://docs.netapp.com/us-en/trident/index.html<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Ftrident%2Findex.html&data=05%7C01%7C%7C19d2e82750b443990ffe08da39721991%7Cc047d5c1d2a6484dae6eec2bce85d023%7C0%7C0%7C637885459468803993%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=b3WNG4EiB5nzirEl5mjojL1ZvmDFpPt%2Ba3zbr0D8EUI%3D&reserved=0>
[https://docs.netapp.com/us-en/trident/images/logo-tophat-social.png]<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Ftrident%2Findex.html&data=05%7C01%7C%7C19d2e82750b443990ffe08da39721991%7Cc047d5c1d2a6484dae6eec2bce85d023%7C0%7C0%7C637885459468960198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yo0ShCJE7rfMtIlSETmg59dIl%2BbzjM8l9QXiMKxVi6o%3D&reserved=0>
Astra Trident 22.04 documentation<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.netapp.com%2Fus-en%2Ftrident%2Findex.html&data=05%7C01%7C%7C19d2e82750b443990ffe08da39721991%7Cc047d5c1d2a6484dae6eec2bce85d023%7C0%7C0%7C637885459468960198%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=yo0ShCJE7rfMtIlSETmg59dIl%2BbzjM8l9QXiMKxVi6o%3D&reserved=0>
Astra Trident is an open source storage provisioner and orchestrator maintained by NetApp. It enables you to create storage volumes for containerized applications managed by Docker and Kubernetes.
docs.netapp.com


***@***.***



Regards,

Iwan



Met vriendelijke groet/Kind regards,
​
Iwan Engelberts • 
Proact Netherlands B.V.
Support Consultant
NL: tel +31 30 30 33 222  •   fax:  +31 30 30 33 210 
BE: tel: +32 2 720 20 91  •  fax:  +32 2 721 72 81
P.O.Box 2393 • 3500 GJ • Utrecht • The Netherlands
Rijnzathe 14 • 3454 PV • Utrecht • The Netherlands
***@***.***  |  
www.proact.eu
# 
ThePowerOfData
 | 
#
ThePowerOfTogether
Proact processes personal information you may provide via email or otherwise in accordance with its privacy notice.ProactNL2020EX001

**Comment by juliantap** [comment]
Hi @eone74  (Iwan :-), 

Though Astra Trident is open source, it is a NetApp product, and the documentation is intended to be used in conjunction with other NetApp product documentation. The Trident docs were rolled into the larger docs.netapp.com library in July of last year to make it easier for customers to move between products in our consolidated library. However, in order to ensure accuracy, we do not duplicate content between product libraries. 

To Chuck's point, the assumption is that clusters are correctly configured for your environment prior to configuring Trident.  

- [Service policies for SVMs](https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html#service-policies-for-data-svms) details the included services for `default-data-blocks` and `default-data-files`. 

- [Configuring LIF service policies](https://docs.netapp.com/us-en/ontap/networking/configure_lif_service_policies.html), details how to configure LIFs for the additional `-services` (iSCSI and others)

I hope this helps!

Thanks!

Julia

**Comment by juliantap** [comment]
Hi @eone74, I am going to close this issue now. If you have more questions, you can still reply to this tread or open a new issue. Thanks!

**Comment by eone74** [comment]
Hi Julia,

Sorry for not getting back tot you but I was discussing your answers with my customer and the NetApp Partner Engineer.
He will inform the NetApp Product guys.

You can archive this case.
Thx.

BR,
Iwan


Met vriendelijke groet/Kind regards,
​
Iwan Engelberts • 
Proact Netherlands B.V.
Support Consultant
NL: tel +31 30 30 33 222  •   fax:  +31 30 30 33 210 
BE: tel: +32 2 720 20 91  •  fax:  +32 2 721 72 81
P.O.Box 2393 • 3500 GJ • Utrecht • The Netherlands
Rijnzathe 14 • 3454 PV • Utrecht • The Netherlands
***@***.***  |  
www.proact.eu
# 
ThePowerOfData
 | 
#
ThePowerOfTogether
Proact processes personal information you may provide via email or otherwise in accordance with its privacy notice.ProactNL2020EX001

**Comment by juliantap** [comment]
Thank you for the confirmation, @eone74 👍
