### ISSUE TITLE
Please re-org install documentation

### ISSUE THREAD

**Issue by DianePatton** [NetAppDocs/trident#147]
Page: [Deploy with Trident operator](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html)

This page implies Step 3 (create trident orchestrator which is under the "Deploy the trident operator manually" section) is only for installing the Trident operator manually., 

However, Step 3 would apply if you installed the Trident operator via Helm too.

So please remove the Step 3 and instead make the "create trident orchestrator" a separate section that applies to either way you install the operator.

**Comment by juliantap** [comment]
@DianePatton, actually, Helm installs TridentOrchestrator for you so there is no additional installation step required. I'll update the heading to make it clear that Helm installs Trident. 

When this change merges, this issue will auto-close. However, if you have any additional comments or questions, just add them & I'll be notified. 

Thanks again!
