### ISSUE TITLE
Trident backend `network` parameter for GCP missing

### ISSUE THREAD

**Issue by juliantap** [NetAppDocs/trident#158]
Page: [Configure a CVS for GCP backend](https://docs.netapp.com/us-en/trident/trident-use/gcp.html)

Add the `network` for GCP to Backend config options table. 
|`network`| GCP network used for CVS volumes, defaults to “default”| “default”

@clintonk, this change will be made back to 21.07 on docs.netapp.com.

**Comment by clintonk** [comment]
Thanks, @juliantap!  This feature went into our GCP driver in August 2019, and it's covered in the RTD pages, so it's perplexing that it isn't in the new docs.
