### ISSUE TITLE
Node prep is missing for CoreOS (from Openshift deployment)

### ISSUE THREAD

**Issue by oleimann** [NetAppDocs/trident#161]
Page: [Prepare the worker node](https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html)

I would think it's identical to RHEL/CentOS, but there may be more changes or different package management ?

**Comment by juliantap** [comment]
Thanks, @oleimann! I'm reaching out to @gnarl & @balaramesh for review & recommendation.

**Comment by gnarl** [comment]
@juliantap, node prep removal from the documentation is going out with the 22.07 release. I believe the mention of worker node preparation at the bottom of the document will be removed with the 22.07 documentation update.

**Comment by juliantap** [comment]
@gnarl Ah, yes, indeed it will. I will link this to that PR and it will resolve when we merge 22.07 to public.

**Comment by juliantap** [comment]
This was resolved with https://github.com/NetAppDocs/trident-internal/pull/89
