### ISSUE TITLE
Show Current Trident Version on Trident Doc Main Page and on Release Notes Page.

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#18]
Show Current Trident Version on Trident Doc Main Page and on Release Notes Page.

The Trident docs are versioned, but there is no way to know which doc version I am viewing currently.
I can assume I am on the latest version, but what version is that?
This can lead to incorrect information with supportability when dealing with different versions.

**Comment by crossond** [comment]
With the ReadtheDocs  doc pages, the version was at least shown in the URL.
With the new doc pages, the current doc version is not clearly displayed anywhere that I can see.
(maybe I am missing it?)

**Comment by juliantap** [comment]
Hi @crossond--thank you for the feedback! No, you aren't missing anything. The idea is, yes, that you are always on the most current version when you are on https://docs.netapp.com/us-en/trident/. 

**However**, I completely see your point. And now that you've mentioned it, I know I've gotten lost in releases as well. I will fix this manually for now. But I'll also bring it up as a possible enhancement for other libraries if others have the same issue. 

Thank you again for the feedback!

**Comment by juliantap** [comment]
Hi @crossond, I've added version number to the landing page and release clarification to the release notes. Thanks again for the feedback!

**Comment by crossond** [comment]
Thank You!
