### ISSUE TITLE
Replace CentOS with Rocky Linux or just add Rocky Linux and Alma Linux

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/trident#183]
This page currently lists CentOS (in two places, for NFS and iSCSI) which in version 7 used to be downstream to RHEL. But since version 8, CentOS is upstream from RHEL (see "Downstream vs. upstream" [here](https://www.centos.org/cl-vs-cs/)). 

I propose that CentOS be replaced with Rocky Linux (which is downstream from RHEL), or alternatively, add Rocky Linux and Alma Linux to the list of RHEL-compatible distros, after CentOS.

Page: [Prerequisites for deployment](https://docs.netapp.com/us-en/trident/trident-docker/prereqs-docker.html)

**Comment by juliantap** [comment]
HI @scaleoutsean, thanks for the feedback. I'll pass this on to the dev team to determine how to handle it.

**Comment by gnarl** [comment]
Hi @scaleoutsean and @juliantap, 

We are not currently qualifying Rocky Linux but do recognize that it has gained support in GCP, AWS, and Azure. It is a requirement that any Operating System that we support or document configuration practices for in the Trident docs is constantly qualified. The [EOL guidance for CentOS 7 ](https://cloud.google.com/compute/docs/eol/centos-eol-guidance) is June 30, 2024 so CentOS can remain on this page.

On this page we can remove mention of Debian.

**Comment by scaleoutsean** [comment]
Okay. 

Maybe we can also change "CentOS" to "CentOS 7" (and not 8 or 9, if those are not qualified), @gnarl?

**Comment by juliantap** [comment]
Thanks, @gnarl & @scaleoutsean. I'll make these changes. When I merge the changes, this issue will auto-close, but you can continue to comment if you have additional comments or questions.
