### ISSUE TITLE
Documentation with wrong URL for container images for Trident 22.07

### ISSUE THREAD

**Issue by MauricioCarmelo** [NetAppDocs/trident#186]
Page: [Requirements](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html)

It seems that the URLs for the container images are incomplete in the documentation for Astra Trident version 22.07

All other versions start with  _k8s.gcr.io/_ and version 22.07 starts with _k8s.io/_.

When I try to pull any image without the .gcr an HTTP 404 error occurs.

**Comment by juliantap** [comment]
Hi @MauricioCarmelo, thank you for the feedback. Let me check with the team on the syntax.

**Comment by juliantap** [comment]
Thanks again, @MauricioCarmelo! This was indeed an oversight. I've corrected this now. This issue will auto-close when I merge to fix. But, feel free to comment here if you have further comments or questions. 

Thank you for reading and contributing the the quality of our docs.
