### ISSUE TITLE
Correction to steps to enable debugging using operator and tridentctl.

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#19]
Page: [Troubleshooting](https://docs.netapp.com/us-en/trident/troubleshooting.html)

If there is not enough information in the Trident logs, you can try enabling the debug mode for Trident by passing the -d flag to the install parameter as follows: 

If Trident was installed with the Operator or Helm:
      # kubectl patch torc <trident-provisioner-name> -n <trident-namespace> --type=merge -p '{"spec":{"debug":true}}'
       (If running Trident version 20.07, 20.10, use tprov in place of torc.)

If Trident was installed with tridentctl:
       ./tridentctl uninstall -n trident  
       ./tridentctl install -d -n trident

Confirm debug is set:
      ./tridentctl logs -n trident
Look for "level=debug msg" in the logs to confirm debug is set.

**Comment by juliantap** [comment]
Hi @crossond -- thank for the feedback! I will review this with engineering and make the appropriate changes. Thanks!

**Comment by juliantap** [comment]
Hi @crossond, Trident engineering agrees with your suggested change with one adjustment. The # kubectl scenario you outline is for Operator-installs only. 

I'll add the additional flag scenario for Helm (`$ helm upgrade <name> trident-operator-21.07.1-custom.tgz --set tridentDebug=true`) as shown in the [Helm upgrade example](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html#upgrade-a-helm-based-operator-installation). 

Please let me know if this addresses your concern. 

Thanks!

J

**Comment by crossond** [comment]
excellent!  thanks!

**Comment by juliantap** [comment]
Hi @crossond -- all done! [Troubleshooting](https://docs.netapp.com/us-en/trident/troubleshooting.html#general-troubleshooting) changes are live. Thanks again!
