### ISSUE TITLE
request for detail about Footnote

### ISSUE THREAD

**Issue by zhenyongnetapp** [NetAppDocs/trident#191]
Page: [Integrate Astra Trident](https://docs.netapp.com/us-en/trident/trident-reco/integrate-trident.html)

from https://docs.netapp.com/us-en/trident/trident-reco/integrate-trident.html#choose-a-backend-driver-for-ontap have below.
Astra Trident offers 2 SAN drivers for ONTAP, whose capabilities are shown below.
and from resize ontap-san is yes while ontap-san-economy is yes with Yes[1]: Not managed by Astra Trident

i have check all doc but not sure what different about above two,  can we have more detail for it(maybe add example),
also other Footnote.

**Comment by juliantap** [comment]
Hi @zhenyongnetapp, thank you for reaching out. The paragraph before the first (ONTAP NAS) table provides clarification for the both tables. Capabilities without the footnote are exposed and be managed through Astra Trident

> Note that, in the tables below, not all of the capabilities are exposed through Astra Trident. Some must be applied by the storage administrator after provisioning if that functionality is desired. The superscript footnotes distinguish the functionality per feature and driver.

Therefore, "resize" for `ontap-san` can be managed through Astra Trident, but `ontap-san-economy` cannot be. Does that answer your question or do you feel that more clarification is needed?

Thanks!

**Comment by zhenyongnetapp** [comment]
Hi

Thanks for quick update.
Em… still not clear about “Therefore, "resize" for ontap-san can be managed through Astra Trident, but ontap-san-economy cannot be”

https://docs.netapp.com/us-en/trident-2204/trident-use/vol-expansion.html#step-2-create-a-pvc-with-the-storageclass-you-created
above doc said
iSCSI volume expansion is supported by the ontap-san, ontap-san-economy, solidfire-san drivers and requires Kubernetes 1.16 and later.

From example use ontap-san , if below example means mangaerd through astra trident?
$ cat storageclass-ontapsan.yaml
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ontap-san
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-san"
allowVolumeExpansion: True


but above said also can expansion supported by ontap-san-economy
and in my case customer use ontap-san-economy with same method just backendtype change from ontap-san to ontap-san-economy.


Thanks

frank

**Comment by juliantap** [comment]
Hi @zhenyongnetapp, OK let me engage the engineering team to better respond to your question. 

Adding @balaramesh & @gnarl for their input.

**Comment by gnarl** [comment]
@juliantap, I agree with @balaramesh that we should update the matrix to remove the [1] superscript for the ontap-san-economy driver.

**Comment by juliantap** [comment]
Thanks @gnarl & @balaramesh. I've removed the footnote for ontap-san-economy & will merge the change.
