### ISSUE TITLE
helm install command doesn't work as written

### ISSUE THREAD

**Issue by bigbosst** [NetAppDocs/trident#194]
Page: [Deploy with Trident operator](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html)

`helm install <release-name> netapp-trident/trident-operator --version 22.4.0 --create-namespace <trident-namespace>`

Error: INSTALLATION FAILED: expected at most two arguments, unexpected arguments: trident

The 'trident' in the error message is what was entered as the `<trident-namespace>`

Create Namespace doesn't take any arguments, only the namespace flag does. For this command to work you would also need a --namespace 

related to https://github.com/helm/helm/pull/7648

the Command would look like this instead

`helm install <release-name> netapp-trident/trident-operator --version 22.4.0 --create-namespace --namespace <trident-namespace>`

Additionally this doc was on the page for astra trident 22.07 I'm not sure if the version is correct in this document or if it's meant to be updated as part of the new version releases tracking the trident versions. It does look like this operator installs the 22.04.0 server version.

```
$ tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 22.04.0        | 22.07.0        |
+----------------+----------------+
```

**Comment by bigbosst** [comment]
As a note, I would also recommend providing expected values for both the <release-name> and <trident-namespace> as much of the documentation expects the t<rident-namespace> to be "trident", for example

**Comment by juliantap** [comment]
Hi @bigbosst -- thank you for your comment & helping improve our docs! I'll investigate this & make any needed changes. 

Adding @gnarl & @balaramesh for input.

**Comment by juliantap** [comment]
Hi @bigbosst, this issue has been fixed with https://github.com/NetAppDocs/trident/pull/217

Thank you again for the feedback!
