### ISSUE TITLE
Replace all referenced to TridentProvisioner and  'tprov': with TridentOrchestrator and 'torc' for doc versions 21.01 and higher.

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#20]
Page: [Upgrade with the operator](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html)

There are several referenced to tprov in the docs for 21.01 and higher.
For doc versions starting with 21.01.0 and higher,  replace all referenced to TridentProvisioner and  'tprov'  ;
with TridentOrchestrator and  'torc'.

Example:

Steps
Verify the status of the existing Trident installation. To do this, check the Status of TridentProvisioner. The status should be Installed.

$ kubectl describe tprov trident -n trident | grep Message: -A 3   

should be:

Verify the status of the existing Trident installation. To do this, check the Status of TridentOrchestrator. The status should be Installed.

$ kubectl describe torc trident -n trident | grep Message: -A 3

**Comment by juliantap** [comment]
Thanks again, @crossond! I'll take this one to engineering as well and make needed changes. Cheers!

**Comment by juliantap** [comment]
Hi @crossond, I've checked with engineering. The section you referenced is specified for version 20.07 - 20.10 and `tprov` is still applicable. The previous section on the page ([Upgrade a cluster-scoped operator installation](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html#upgrade-a-cluster-scoped-operator-installation)) is documented for upgrades for 21.10 and later. 

**However**, this  entire topic is marked for expansion and reorganization. In an upcoming update, we will add additional sections to cover a wider range of upgrade options, such as the following:  

- Upgrade tridentctl based installations
- Upgrade Operator based installation (should include both tprov to torc and torc to torc)
- Upgrade Helm based installation
- Cross installation upgrades:
  - tridentctl to Operator
  - tridentctl to Helm
  - Operator to tridentctl
  - Operator to Helm
  - … etc

I'll leave this issue open until the end of the week in case you have additional questions or comments. Thanks again for your feedback!

J
