### ISSUE TITLE
 Is the access-mode accurate for ontap-san and ontap-san-economy in Trident docs.netapp.com?

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#201]
Page: [ONTAP drivers](https://docs.netapp.com/us-en/trident/trident-concepts/ontap-drivers.html)

Q: Is the access-mode accurate for ontap-san and ontap-san-economy on this page?
     > Should  'ROX'  and  'RWX'  be listed  for san ?
        If so,  for what use-case would this work?

**Driver                        | Protocol | VolumeMode | Access modes supported | File systems supported**
ontap-san                 | iSCSI       | Block              | RWO,**ROX,RWX**           | No Filesystem. Raw block device
ontap-san-economy | iSCSI       | Block              | RWO,**ROX,RWX**           | No Filesystem. Raw block device

...............................................

**Reference the above against the following Kubernetes doc page:**  
https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Volume Plugin | ReadWriteOnce | ReadOnlyMany | ReadWriteMany | ReadWriteOncePod**
iSCSI                |           ✓              |           ✓             |            -              |            -

**Comment by crossond** [comment]
Thank you!

**Comment by juliantap** [comment]
Hi @crossond,

iSCSI can run in either "block" or "filesystem" VolumeMode. Only filesystem mode restricts read-write access.

- In "block" VolumeMode with no filesystem (raw block device), `onstap-san` & `ontap-san-economy` can be RWX. 
- In "Fliesystem" VolumeMode, they can be only RWO & ROX.

Does this answer the question?

Thanks!

J

**Comment by crossond** [comment]
Hi @juliantap 
Yes it answers the question and Thank you.  
Can the response above be included/shared in the Trident docs so it is accessible and helpful for customers and support?   Perhaps a footnote for the ontap-san and ontap-san-economy drivers? It is a discussion that has occurred with customers, and likely will again at some point.  
Regards,
David Crosson
