### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by patric0303** [NetAppDocs/trident#208]
Page: [Frequently asked questions](https://docs.netapp.com/us-en/trident/faq.html) 

How do I set volume encryption through Astra Trident with ONTAP?
You can set encryption on the volume provisioned by Trident by using the encryption parameter in the backend definition file. For more information, refer to: [How Astra Trident works with NVE and NAE](https://docs.netapp.com/us-en/trident-reco/security-reco.html) 
Link is broken.

**Comment by juliantap** [comment]
Hi @patric0303 -- thank you for catching and reporting this! I'm merging the fix now. This ticket will auto-close but you can continue to comment here if needed. 

Thank you!

J
