### ISSUE TITLE
Is find_multipath=yes  and scanning configs correct for Docker Plugin?  

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#215]
Page: [Prerequisites for deployment](https://docs.netapp.com/us-en/trident/trident-docker/prereqs-docker.html)

Are the find_multipath=yes  and scanning configs correct for **Docker Plugin**?  
They are different from the K8S deployment.   Why?
This is confusing for support and customer.  Can some info about these be provided if they are different for Docker?

4. Enable multipathing:
   sudo tee /etc/multipath.conf <←'EOF'
   defaults {
   user_friendly_names yes
   **find_multipaths yes**

All other Trident documentation (K8S and general, including Release Notes) show this option should be "find_multipath=no"

2. What is the correct setting for iscsid.conf  scanning for DOCKER PLUGIN?
For K8S,  the docs show  
Set scanning to manual:
sudo sed -i 's/^\(node.session.scan\).*/\1 = manual/' /etc/iscsi/iscsid.conf

Reference: https://docs.netapp.com/us-en/trident-2207/trident-use/worker-node-prep.html#iscsi-volumes

**Comment by juliantap** [comment]
Thanks, @crossond!

Adding @gnarl & @balaramesh for assistance.

**Comment by balaramesh** [comment]
Hello @juliantap 


We will need to update the bullet points under the iSCSI line items (for RHEL and Ubuntu) to contain the same information provided here in the section iSCSI: https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html#iscsi-volumes 

Please add me as a reviewer to the PR. I will take a look at it!

Thanks!

**Comment by crossond** [comment]
Something additional to consider is Docker Swarm vs Docker Plugin.  for the current customer case, they are using Docker Swarm, for which there is no help in Trident Documentation.

Note/suggestion from support engineer working with this customer:
_"Docker Swarm is a multi-node (Cluster) setup, where you want the igroup to contain all IQNs.
 To limit issues with Multipathing refreshes causing access errors from the using Node, that setting should be **no** in this case.
 For a single Docker Host, the find_multipaths may as well be **yes.**"_

If engineering confirms the above, could this helpful information be included in Trident docs?

**Comment by juliantap** [comment]
Hi @crossond, I've merged the initial fix per @balaramesh and he'll also review your last comment. Thanks!
