### ISSUE TITLE
Please update content to 21.10

### ISSUE THREAD

**Issue by victorfrancoramos** [NetAppDocs/trident#218]
Page: [Deploy Astra Trident](https://docs.netapp.com/us-en/trident/trident-docker/deploy-docker.html)
Code "docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:21.07 config=myConfigFile.json" should be updated to "docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:21.10 config=myConfigFile.json"

**Comment by juliantap** [comment]
HI @victorfrancoramos, thank you for the feedback & contributing to the quality of our documentation. When this issue is resolved, this ticket with auto-close but you can continue to make comments. Thanks!

**Comment by juliantap** [comment]
Hi @victorfrancoramos, we have removed the hard-coded version number from the command and added a notation to replace the `<version`> variable with the desired version. This ensures long-term accuracy of the documentation. Thank you again for your feedback!
