### ISSUE TITLE
Trident bundle.yaml is no longer in /deploy dir, and instructions for pre/post1_25 yaml is unclear (2nd of 2)

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#226]
Page: [Deploy with Trident operator](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html)

This doc change is for the deployment section of the docs.

References to bundle.yaml is no longer working, as this file is missing in 22.10.
This causes upgrades and installs to fail.
Also, per customer, the instructions are not exactly clear on when to use bundle.yaml|bundle_pre_1_25.yaml|bundle_post_1_25.yaml
Please add clarification to the instructions for deployment and for upgrades with operator and/or helm as appropriate.

ex:
 "kubectl delete -f 22.01/trident-installer/deploy/bundle.yaml -n trident"
 "kubectl create -f 22.10.0/trident-installer/deploy/bundle.yaml -n trident"

The files in 22.01/trident-installer/deploy/bundle.yaml  are (**bundle_post_1_25.yaml** and **bundle_pre_1_25.yaml**) 
as shown below:
# pwd
/root/22.10/trident-installer/deploy
# ls
**bundle_post_1_25.yaml**  clusterrolebinding.yaml  crds                namespace.yaml  podsecuritypolicy_unprivileged.yaml
**bundle_pre_1_25.yaml**   clusterrole.yaml         kustomization.yaml  operator.yaml   serviceaccount.yaml

**Comment by juliantap** [comment]
Hi @crossond, these changes have been made on PR #229 

Thanks!

J
