### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/trident#227]
Page: [Deploy with Trident operator](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html)

Manually: Trident provides a [bundle.yaml](https://github.com/NetApp/trident/blob/master/deploy/bundle.yaml) file that can be used to install the operator and create associated objects.

Link is broken - it seems bundle.yaml doesn't exist anymore but two new files that are necessary because of the changes in K8s 1.25?

**Comment by juliantap** [comment]
Hi @ntap-johanneswagner, thank you for pointing this out! I'll update the docs to reference the pre- and post- 1.25 bundle versions.

**Comment by juliantap** [comment]
Hi @ntap-johanneswagner, this has been fixed on PR #229 

Thank you!

J
