### ISSUE TITLE
snapshot controller for Openshift

### ISSUE THREAD

**Issue by ajay-malhotra-ntp** [NetAppDocs/trident#231]
Page: [Work with snapshots](https://docs.netapp.com/us-en/trident/trident-use/vol-snapshots.html)
Under section "Deploying a volume snapshot controller", please add a note:
If using Openshift, move to "Step 1: Set up a VolumeSnapshotClass"

**Comment by juliantap** [comment]
Hi @ajay-malhotra-ntp, thank you for the feedback. I'll speak with the team to determine the best way to handle this.

**Comment by juliantap** [comment]
Hi @ajay-malhotra-ntp I hope the updates to this topic make it easier to get directly to the information you need. Feel free to comment back if you have additional comments. Thank you for contributing!!
