### ISSUE TITLE
Update iSCSI CHAP info to indicate Element OS 12.7 doesn't require MD5

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/trident#233]
Page: [Prepare the worker node](https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html)

Current: If using RHCOS version 4.5 or later, or other RHEL-compatible Linux distribution, with the solidfire-san driver, ensure that the CHAP authentication algorithm is set to MD5 in /etc/iscsi/iscsid.conf.

Next: If using RHCOS version 4.5 or later, or other RHEL-compatible Linux distribution, with the solidfire-san driver and Element OS 12.5 or earlier, ensure that the CHAP authentication algorithm is set to MD5 in /etc/iscsi/iscsid.conf. Beginning with Element 12.7, secure FIPS compliant CHAP algorithms SHA1, SHA-256, and SHA3-256 are supported.

MD5 limitation was removed in 12.7 [here](https://docs.netapp.com/us-en/element-software/storage/task_data_manage_accounts_work_with_accounts_task.html#chap-algorithms)

**Comment by juliantap** [comment]
Hi @scaleoutsean, sorry for the delay on this! The docs have been updated to reflect the FIPS-compliant algorithms are available with Element 12.7. Thank you for the feedback!
