### ISSUE TITLE
Number of operators supported by Virtual Storage Pools

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#237]
Page: [Virtual storage pools](https://docs.netapp.com/us-en/trident/trident-concepts/virtual-storage-pool.html)

Hi,

this page says that 6 operators are currently supported, even though the table shows only 4 of them.

In the legacy documentation 'readthedocs', Trident indeed supported 6 operators.
https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/concepts/virtual_storage_pools.html?highlight=virtual%20storage%20pools

I suppose we have either removed 2 operators from Trident or forgotten to add 2 the new doc page

++

**Comment by juliantap** [comment]
Hi @YvosOnTheHub, thank you for pointing this out. I'll verify and get the docs corrected. Thanks!

Adding @balaramesh & @gnarl
