### ISSUE TITLE
Note on adaptiveQosPolicy not compatible with ontap-nas-economy driver

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#240]
Page: [ONTAP NAS configuration options and examples](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html)

The table "Backend configuration options for provisioning volumes" lists the parameter adaptiveQosPolicy. This parameter is valid for the ontap-nas driver but does not work with the ontap-nas-economy driver. Trident will trow this error:

"Failed to create backend: problem initializing storage driver 'ontap-nas-economy': error validating ontap-nas-economy driver: storage pool validation failed: qtrees do not support adaptive QoS policies"

It would be good to mention this in the docs. Below the table there already is a note on QoSPolicy in general. Maybe a remark about the ontap-nas-economy limitation could be added there?

**Comment by juliantap** [comment]
Hi @wonderland, there is a note in the table but maybe it isn't obvious enough. I will add a space between the rest of the text and that last sentence to make it more visible. Thanks!

![image](https://user-images.githubusercontent.com/83591660/211599225-1913cfa8-fdd9-48f8-96e1-943071d4646c.png)

**Comment by wonderland** [comment]
Oops, completely missed that, sorry. Yes, maybe a blank or even newline would be helpful for people with a lack of concentration (like myself) ;-)

**Comment by juliantap** [comment]
The fix is on its way! This will auto-close but comment and let me know if this doesn't improve it :-)
