### ISSUE TITLE
Remove eseries-iscsi driver

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#241]
Page: [Kubernetes and Trident objects](https://docs.netapp.com/us-en/trident/trident-reference/objects.html)

This page still lists eseries-iscsi driver in multiple places. This driver has been removed from Trident, I think it should be cleaned from the docs as well.

**Comment by juliantap** [comment]
Hi @wonderland, thanks for catching this. I'll check with the team and get this updated.

**Comment by juliantap** [comment]
Fixed @wonderland -- thanks again!
