### ISSUE TITLE
Duplicate parameters

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#246]
Page: [ONTAP NAS configuration options and examples](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html)

Hi,
2 parameters appear twice in the "options" table:
- snapshotDir
- exportPolicy

I believe they should only appear once.
++

**Comment by juliantap** [comment]
Hi @YvosOnTheHub, sorry for the delay! Thank you for catching this. I'll get it fixed ASAP.
