### ISSUE TITLE
Warning about nas-economy

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/trident#248]
Page: [ONTAP drivers](https://docs.netapp.com/us-en/trident/trident-concepts/ontap-drivers.html)

we should include the warning from page https://docs.netapp.com/us-en/trident/trident-use/ontap-nas.html: 

Customers must use the ontap-nas driver for production workloads that require data protection, disaster recovery, and mobility. Astra Control provides seamless protection, disaster recovery, and mobility for volumes created with the ontap-nasdriver. The ontap-nas-economy driver should be used only in limited use cases where anticipated volume usage is expected to be much higher than what ONTAP supports, with no anticipated data protection, disaster recovery, or mobility (moving volumes between Kubernetes clusters) requirements.

also on this page.

**Comment by juliantap** [comment]
Hi @ntap-johanneswagner, sorry for the delay! I agree this should also be added here--thank you for the suggestion! I'll get this updated ASAP.
