### ISSUE TITLE
doc clarifications to consider...

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/trident#254]
Page: [Upgrade with the operator](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html)

Please consider adding two details to this page and other similar pages:

1 - When running kubectl commands that are referencing a relative path to a trident installation directory, spell out this fact prior to showing the command execution.  If someone is maintaining a Trident installation from a different host than the one it was installed from, or if the installation source has been removed... they will need to download the version they want to *uninstall* so they can run the command to remove it.

2 - When referencing commands that require the <trident-orchestrator-name> parameter, include information on how to discover this information:  kubectl get torc -n <namespace>

The above information would have saved me quite a bit of time yesterday, and I'm hoping it will be helpful to a current/future customer.  :)  Thanks!

**Comment by juliantap** [comment]
@mdmiller99 Thank you for the feedback and contributing to the quality of our documentation! I'll work with the team on your recommendation.

**Comment by balaramesh** [comment]
Hello @mdmiller99 

Which code-blocks are you referring to? The code blocks provided in this page have a comment call out that asks to check if in the right directory. This can be improved upon.

In addition, the code-blocks listed on this page are designed to be executed sequentially. That explains the relative path for some commands.

With reference to (2), the `kubectl get torc` command is namespace-agnostic. Can I please know the version of Trident you used this command with? I would like to make sure it is still namespace-agnostic.

Thank you!

**Comment by mdmiller99** [comment]
It was an older release, Trident 21.10

**Comment by juliantap** [comment]
Hi @mdmiller99, I am trying to figure out the best way to address your first comment. I could not find an example on that page where we don't stipulate that you must use the version specific to your configuration. Such as, 

> Delete the Trident operator that was used to install the current Astra Trident instance. For example, if you are upgrading from 22.01, run the following command:

Can you provide the specific example that was troublesome? I'm happy to make some clarifications.

For question 2, did the response from @balaramesh resolve the issue? I believe `kubectl get torc` was also namespace-agnostic in 21.10.

**Comment by mdmiller99** [comment]
Sorry, I didn't realize these git issues didn't link to the page they were created from for reference.  It has been a while, and I do not have the environment handy to re-test the necessity of the namespace for the command.  As I've moved on to other efforts, let's just close this one for now.  Next time I report a doc change request, I'll be sure to copy the doc URL into the git issue.  Thanks!

**Comment by juliantap** [comment]
Sorry, @mdmiller99! It does include the page, if that helps: https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html

**Comment by mdmiller99** [comment]
ah, thanks for pointing that out.  Cool.  Ok... for this step:

Delete the Trident operator that was used to install the current Astra Trident instance. For example, if you are upgrading from 22.01, run the following command:

kubectl delete -f 22.01/trident-installer/deploy/bundle.yaml -n trident


I think this is obvious to those daily working with Trident, but if I were an admin that had inherited an environment I needed to support, it would be helpful to call out the need to locate the 22.01 source directory (and re-download this if needed) before running the above step.  I'm still new to working with K8s, but I'm increasingly concerned with the number of things that must be maintained outside of etcd.  Ideally we could discover what is needed from the cluster for the delete command... without requiring previous installation sources for the deletion.

The second point was... upon inheriting an unfamiliar configuration to support... spelling out how to list the current Trident version in use... which was the kubectl get torc command.  This is a prerequisite to locating the install package and executing the above delete command.

**Comment by juliantap** [comment]
@mdmiller99 gotcha! Ok, this makes sense to me. I'm going to reopen this issue. Give me a bit of time to work on the wording and I'll let you know when it's ready.
