### ISSUE TITLE
Steps to configure Cloud Volumes ONTAP as backend storage

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/trident#26]
Page: [Configure backends](https://docs.netapp.com/us-en/trident/trident-use/backends.html)

It's not clear which option I should choose to learn how to configure Cloud Volumes ONTAP as backend storage for a Kubernetes cluster.

**Comment by juliantap** [comment]
Hi @netapp-bcammett, thanks for the feedback. I'll review and ask the dev team.

**Comment by netapp-bcammett** [comment]
Julia,

I'm not familiar with the Trident installation process, but do the two bullets on the page in question apply to Cloud Volumes ONTAP?

![image](https://user-images.githubusercontent.com/18287750/144443053-516c11ca-63ae-4ca1-87d1-d10941dacc3a.png)

**Comment by juliantap** [comment]
Merged--thanks!
