### ISSUE TITLE
Mistake between ontap-nas-economy and ontap-nas in the examples

### ISSUE THREAD

**Issue by wjeremynetapp** [NetAppDocs/trident#262]
Page: [ONTAP NAS configuration options and examples](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html)

Hi, about half way down the page under Auto Export Policy, it looks like either the header or the example needs to be changed to ontap-nas or ontap-nas-economy.

The snippet from the page is:

Auto export policy
These examples show you how you can instruct Astra Trident to use dynamic export policies to create and manage the export policy automatically. This works the same for the ontap-nas-economy and ontap-nas-flexgroup drivers.

ontap-nas-economy driver    <<<<<<<<<<<<header
{
    "version": 1,
    "storageDriverName": "ontap-nas",  <<<<<<<<<<example
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "svm": "svm_nfs",
    "labels": {"k8scluster": "test-cluster-east-1a", "backend": "test1-nasbackend"},
    "autoExportPolicy": true,
    "autoExportCIDRs": ["10.0.0.0/24"],
    "username": "admin",
    "password": "secret",
    "nfsMountOptions": "nfsvers=4",
}

**Comment by juliantap** [comment]
@wjeremynetapp thank you for catching this! Let me confirm which way we intended to go (header or sample) and get that fixed. This issue will auto-close when I merge the fix, but you are welcome to comment on it again at any point in the future.

**Comment by wjeremynetapp** [comment]
Awesome.  Thanks!

Thank You
Jeremy Watts
Technical Support Engineer
Technical Support Center
NetApp
***@***.******@***.***>
netapp.com<http://www.netapp.com/us/>

My normal working hours are Monday to Friday, 1:00 pm - 9:00 pm EST.

For technical assistance on a new or existing case, please call:
*US & Canada 888-4-NETAPP // *EMEA/Europe 00-800-44-638277 // *Asia/Pacific 800-8008-0800

You may also get support on the Web at http://mysupport.netapp.com<http://mysupport.netapp.com/>
