### ISSUE TITLE
Parameter names not properly localized

### ISSUE THREAD

**Issue by netapp-dbagwell** [NetAppDocs/trident#264]
Page: [Prepare to configure a backend with ONTAP NAS drivers](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html)

@juliantap take a look at parameter names in https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html#enable-certificate-based-authentication if translated. You'll find incorrect English and mixtures of spaces and camelCase/pascal case because NMT is interpreting these as regular text. I'd recommend adding a code style to these and other similar instances throughout the doc set.

**Comment by juliantap** [comment]
@netapp-dbagwell I'm going to close this as a dupe to fix under our larger conversion from JSON to YAML (https://github.com/NetAppDocs/trident-internal/issues/215). This should catch the majority of issues.
