### ISSUE TITLE
Add step/instruction needed for SVM-DR Recovery workflow if SVM-DR is without network identity retention.

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#268]
Page: [Data protection](https://docs.netapp.com/us-en/trident/trident-reco/backup.html)

Item 6:
6. Update all the required backends to reflect the new destination SVM name by running the ./tridentctl update backend <backend-name> -f <backend-json-file> -n <namespace> command.
........................

- For use case where SVM-DR is created using either -identity-preserve false, and/or -discard-configs network; 
  (ie. the SVM-DR is a different IP/subnet):
  Add instruction for changing mgmtLIF and dataLIF on the backend.json.

Q:  Would the new feature in 23.01 to change dataLIF be required?
     https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html#update-datalif-after-initial-configuration

**Comment by juliantap** [comment]
Adding @balaramesh, @clintonk, & @gnarl for assistance.
