### ISSUE TITLE
Review DR scenarios and steps for SVM-DR and Volume Snapmirror Replication

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#274]
Page: [Data protection](https://docs.netapp.com/us-en/trident/trident-reco/backup.html)

**Several questions and steps for the DR scenarios of  'SVM-DR' and  'Volume Snapmirror Replication'**
**Review Steps listed in sections for duplication and clarity.**

Heading:  Snapmirror Volume Replication
   subHeading:  'SnapMirror volume disaster recovery workflow for Trident'
    https://docs.netapp.com/us-en/trident/trident-reco/backup.html#snapmirror-volume-replication
   _"The following steps describe how to recover a single master Kubernetes cluster with Astra Trident."_

**-> the subsection: 'SnapMirror volume disaster recovery workflow for Trident'  seems to be duplicate of:**

Heading:  Snapmirror Storage Virtual Machines (SVM) replication
    subHeading:  'Disaster recovery workflow for Trident'    
     https://docs.netapp.com/us-en/trident/trident-reco/backup.html#snapmirror-storage-virtual-machines-svm-replication
     _"The following steps describe how to recover a single master Kubernetes cluster with Astra Trident in the event of a disaster:"_
      -> what specific disaster is this for?  SVM-DR?   or Volume Snapmirror Restore?

**Except for Step 6 :** 

'Snapmirror Volume Replication'  :  'SnapMirror volume disaster recovery workflow for Trident'
Step 6: _"Clean up the previous backends and create new backends on Trident. Specify the new management LIF, new SVM name, and password of the destination SVM."_

'Snapmirror Storage Virtual Machines (SVM) replication'  :   'Disaster recovery workflow for Trident'  
Stepp 6:  _"Update all the required backends to reflect the new destination SVM name by running the ./tridentctl update backend <backend-name> -f <backend-json-file> -n <namespace> command."_

**And the Note:**
_"For application persistent volumes, when the destination SVM is activated, all the volumes provisioned by Trident start serving data. After the Kubernetes cluster is set up on the destination side by using the steps outlined above, all the deployments and pods are started and the containerized applications should run without any issues."_

->  **Why are these steps needed for Volume Snapmirror Replication?**
      Heading:  Snapmirror Volume Replication  :     subHeading:  'SnapMirror volume disaster recovery workflow for Trident'

..........................

For Heading:  Snapmirror Volume Replication 
   subHeading:   Disaster recovery workflow for application persistent volumes

_1. Stop all the scheduled SnapMirror transfers and abort all ongoing SnapMirror transfers. Break the replication relationship between the destination and source volume so that the destination volume becomes read/write. Clean up the deployments which were consuming PVC bound to volumes on the source SVM._

--> **Why is "clean up the deployments, PVCs and PV, from the Kubernetes cluster." ** 
Please provide more detail about the exact situation.  are we just restoring a volume to the k8s cluster?  
Is this an application PVC/PV mounted in a pod?   instead of deployments, should we state including 'pods, pvcs, pvs'?
Should this be done before or after the import step?

_2. After the Kubernetes cluster is set up on the destination side by using the steps outlined above, clean up the deployments, PVCs and PV, from the Kubernetes cluster._

--> **Why is new K8S cluster needed to restore 1 volume from its destination SVM?
      Is this for restoring the Kubernetes etcd stored in ONTAP volume to a new K8S cluster?**

**Comment by juliantap** [comment]
This will be combined with #268
