### ISSUE TITLE
Include details to deploy Trident on Windows with Helm and other install methods

### ISSUE THREAD

**Issue by balaramesh** [NetAppDocs/trident#280]
Page: [Deploy Trident operator using Helm (Standard mode)](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-helm.html)

An internal user reported today that there are no details available on this page that explain deploying Trident on Windows nodes.

```When you look at those docs, there is no indication you need that flag, nor do you know that the options are. We need to know what the options are. A table will work to.```

**Comment by juliantap** [comment]
@balaramesh Wouldn't they use the same config options as: https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy.html? If so, I can add links to the config options page.

**Comment by balaramesh** [comment]
@juliantap not quite. We will need a new table to document the options for the Helm chart. these values are shown here: https://github.com/NetApp/trident/blob/d11d0c6ad3578d969cbb9ce7dfa1b763740812c4/helm/trident-operator/values.yaml
