### ISSUE TITLE
Virtual storage pool examples 

### ISSUE THREAD

**Issue by sjpeeris** [NetAppDocs/trident#290]
Page: [ONTAP SAN configuration options and examples](https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html)

"The first StorageClass (protection-gold) will map to the first, second virtual pool in the ontap-nas-flexgroup backend and the first virtual pool in the ontap-san backend. These are the only pool offering gold level protection."

When we say - "first, second virtual pool in the ontap-nas-flexgroup backend", which backend are we referring to ? Does the user expect to see an example of the backend being referred to in this page ?

**Comment by juliantap** [comment]
Hi @netapp-chandaj, I am still awaiting final approval on the changes. I'll follow up with the reviewers.
