### ISSUE TITLE
tridentctl backend update

### ISSUE THREAD

**Issue by sjpeeris** [NetAppDocs/trident#291]
Page: [Prepare to configure a backend with ONTAP NAS drivers](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html)

"Then use the updated backend.json file containing the required parameters to execute tridentctl backend update."

In the example below, we have "tridentctl update backend NasBackend -f cert-backend-updated.json -n trident". 

In that case, should we say "hen use the updated backend.json file containing the required parameters to execute **tridentctl update backend"**

**Comment by juliantap** [comment]
@sjpeeris These other two will take me a little longer. I'll get them done over the weekend or first of next week.
