### ISSUE TITLE
volume import doc should be more clear on 'minimal' configuration needed.

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#299]
Page: [Import volumes](https://docs.netapp.com/us-en/trident/trident-use/vol-import.html)

Support continues to have customer cases where customer inputs all or too many parameter/details from the PVC into the PVC yaml;  and this causes the import command to fail.
There are several KB's on importing volumes, however we suggest the docs could be more clear.

_"The Persistent Volume Claim (PVC) file is used by the volume import process to create the PVC. At a minimum, the PVC file should include the name, namespace, accessModes, and storageClassName fields as shown in the following example."_

The wording above should clarify :  
The pvc.yaml for importing should only have the minimal data shown in the example below.  and specifically state "Do Not include the PV name, volume size, annotations, etc..." (these are the common mistakes which cause the import to fail).  Follow the pvc.yaml example below.

The pvc.yaml example image is good.

............

In the paragragh below the example, specify the 'tridentctl import command'.  
This can further emphasize the point.  (As it reads currently, this may be why customers include the volume name in the pvc.yaml.)

_"To import a storage volume, specify the name of the Astra Trident backend containing the volume, as well as the name that uniquely identifies the volume on the storage (for example: ONTAP FlexVol, Element Volume, CVS Volume path)."_

_"To import a storage volume, **use the tridentctl import command to** specify the name of the Astra Trident backend containing the volume, as well as the name that uniquely identifies the volume on the storage (for example: ONTAP FlexVol, Element Volume, CVS Volume path)."_

**Comment by juliantap** [comment]
Thanks @crossond! Per our chat, I'll pick this up on Monday :-)
