### ISSUE TITLE
Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

### ISSUE THREAD

**Issue by netapp-dgrund** [NetAppDocs/trident#300]
Page: [Prepare to configure a backend with ONTAP NAS drivers](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html)
doc needs to state:
 Astra Trident supports SMB volumes mounted to pods running on Windows nodes only.

**Comment by juliantap** [comment]
@netapp-dgrund Thank you for the feedback! I'll review this with the team & make needed updates. This issue will auto-close when the change is made, but you can continue to comment here. Thank you again for contributing to the quality of our documentation!
