### ISSUE TITLE
URL path for Container images and corresponding Kubernetes versions are incorrect

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#308]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions

### Page title

url path for Container images and corresponding Kubernetes versions are incorrect

### Summary

1.  **Doc page shows:**   'k8s.io'    This is incorrect and is redirected to  'registry.k8s.io'
       # docker pull of k8s.io returns HTTP 404 error.
       # docker pull of registry.k8s.io  is successful

netapp/trident:23.04.0
netapp/trident-autosupport:23.04
**k8s.io**/sig-storage/csi-provisioner:v3.4.1
k8s.io/sig-storage/csi-attacher:v4.2.0
k8s.io/sig-storage/csi-resizer:v1.7.0
k8s.io/sig-storage/csi-snapshotter:v6.2.1
k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0
netapp/trident-operator:23.04.0 (optional)

**Lab Example:**
**/tridentctl images --k8s-version v1.25.0**
+--------------------+--------------------------------------------------------------+
| KUBERNETES VERSION |                       CONTAINER IMAGE                        |
+--------------------+--------------------------------------------------------------+
| v1.25.0            | netapp/trident:23.04.0                                       |
|                    | docker.io/netapp/trident-autosupport:23.04                   |
|                    | **registry.k8s.io**/sig-storage/csi-provisioner:v3.4.1           |
|                    | registry.k8s.io/sig-storage/csi-attacher:v4.2.0              |
|                    | registry.k8s.io/sig-storage/csi-resizer:v1.7.0               |
|                    | registry.k8s.io/sig-storage/csi-snapshotter:v6.2.1           |
|                    | registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.7.0 |
|                    | netapp/trident-operator:23.04.0 (optional)                   |

2.   This matters if customer is using proxy server and needs to update their whitelist to allow specific url access.
      Seen this in 1 customer case.    The docs should have the full correct list of URLs.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@crossond thanks for pointing this out. I'm updating the requirements for this and previous version after K8s updated the registry location.
