### ISSUE TITLE
Add OpenShift 4.9 to the list of supported orchestrators

### ISSUE THREAD

**Issue by balaramesh** [NetAppDocs/trident#31]
Page: [Requirements](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html)

The content on the requirements page must be updated as follows:

```
Astra Trident supports multiple container engines and orchestrators, including the following:

    Kubernetes 1.17 or later (latest: 1.22)

    Mirantis Kubernetes Engine 3.4

    OpenShift 4.4, 4.5, 4.6 (4.6.8+), 4.7, 4.8, 4.9 (latest 4.9)

The Trident operator is supported with these releases:

    Kubernetes 1.17 or later (latest: 1.22)

    OpenShift 4.4, 4.5, 4.6 (4.6.8+), 4.7, 4.8, 4.9 (latest 4.9)
```

**Comment by gnarl** [comment]
Hi @juliantap and @balaramesh, I wanted to be part of the review for this change as the OpenShift information is not correct. Can we get another PR opened?

**Comment by juliantap** [comment]
Sorry, Chuck. For some reason I'm unable to add you as a reviewer in either /trident or /trident-internal. I am submitting the request to have you added to both repos so that I can add you, but I don’t know how long it will take. 

What are the changes that need to be made? I’ll create the pull request and email the changes text to you for review.

**Comment by juliantap** [comment]
@gnarl Well, now I can tag you at least. Here's the change in case I still can't add you for PR review. 

*****************
Astra Trident supports multiple container engines and orchestrators, including the following:

- Kubernetes 1.17 or later (latest: 1.22)
- Mirantis Kubernetes Engine 3.4
- OpenShift 4.7, 4.8, 4.9 (latest 4.9)

The Trident operator is supported with these releases:    

- Kubernetes 1.17 or later (latest: 1.22) 
- OpenShift 4.7, 4.8, 4.9 (latest 4.9)

*****************

**Comment by gnarl** [comment]
Hi @juliantap, I opened a new issues with the changes that need to be made. https://github.com/NetAppDocs/trident/issues/33

We can have a conversation on that issue if needed. If you or @balaramesh have questions on how we are determining what OpenShift versions we are supporting we can talk about it there.

Thanks for making the request to get me the access needed on the repo.

**Comment by juliantap** [comment]
Closing this and creating new PR on @gnarl issue request.
