### ISSUE TITLE
RWOP access mode support

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#311]
### Page URL

https://docs.netapp.com/us-en/trident/trident-concepts/ontap-drivers.html

### Page title

ONTAP drivers

### Summary

Hi,
now that Trident supports RWOP access mode, this page should reflect it in the protocol/driver table
++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Thank you @YvosOnTheHub I'll confirm with the team and get the changes made.
