### ISSUE TITLE
determining previous trident install method

### ISSUE THREAD

**Issue by mdmiller99** [NetAppDocs/trident#314]
Page: [Upgrade with the operator](https://docs.netapp.com/us-en/trident-2210/trident-managing-k8s/upgrade-operator.html)

It would be helpful to spell out how one can determine the original trident install method so they can follow the correct document steps that follow.  Consider adding something like this to the top of the upgrade section (for all trident versions):

how to tell which install method was used for trident?
- if there is an orchestrator pod, it was either helm or trident orchestrator only deployment
- describe the orchestrator pod, if there are helm labels, it was installed with helm
- if there is no orchestrator pod, it was installed with tridentctl

**Comment by clintonk** [comment]
s/orchestrator/operator

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Matt Miller ***@***.***>
Sent: Wednesday, June 28, 2023 6:19:28 PM
To: NetAppDocs/trident ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NetAppDocs/trident] determining previous trident install method (Issue #314)

NetApp Security WARNING: This is an external email. Do not click links or open attachments unless you recognize the sender and know the content is safe.




Page: Upgrade with the operator<https://docs.netapp.com/us-en/trident-2210/trident-managing-k8s/upgrade-operator.html>

It would be helpful to spell out how one can determine the original trident install method so they can follow the correct document steps that follow. Consider adding something like this to the top of the upgrade section (for all trident versions):

how to tell which install method was used for trident?

  *   if there is an orchestrator pod, it was either helm or trident orchestrator only deployment
  *   describe the orchestrator pod, if there are helm labels, it was installed with helm
  *   if there is no orchestrator pod, it was installed with tridentctl

**Comment by juliantap** [comment]
Hi @mdmiller99, we added the requested information and made additional improvements to clarify the upgrade process. This issue has auto-closed, but you can continue to comment here if you have questions. Thank you for contributing the quality of NetApp docs!
