### ISSUE TITLE
Drivers & SMB

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#324]
### Page URL

https://docs.netapp.com/us-en/trident/trident-concepts/ontap-drivers.html

### Page title

ONTAP drivers

### Summary

Hi,
now that Trident supports SMB with ONTAP, it would be great to update this page & reflect which access modes are supported (as well as filesystem, etc...)
thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@YvosOnTheHub thanks for the feedback. I'll confer with the team and get the changes made.

**Comment by juliantap** [comment]
@YvosOnTheHub this has been fixed. Thanks!
