### ISSUE TITLE
ONTAP-NAS-ECO & RWOP

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#325]
### Page URL

https://docs.netapp.com/us-en/trident/trident-concepts/ontap-drivers.html

### Page title

ONTAP drivers

### Summary

Hi
any reason why the NAS-ECO driver is not listed as compatible with RWOP ?
++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@YvosOnTheHub Not sure how I missed that! Yes, it should be. Adding it now. Thank you!
