### ISSUE TITLE
controllerPluginNodeSelector appears twice in the list of parameters

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#327]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy.html

### Page title

Customize Trident operator installation

### Summary

Hi, 

the parameters _controllerPluginNodeSelector_ & _controllerPluginTolerations_ appear twice in the table that lists the TridentOrchestator attributes.

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Hi @YvosOnTheHub I actually caught this as part of a a different PR. This correction will go live when the 23.07 changes go live. Thank you!
