### ISSUE TITLE
Pass the option '-n' to the kubectl to specify the namespace

### ISSUE THREAD

**Issue by amej** [NetAppDocs/trident#328]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html

### Page title

Upgrade Astra Trident

### Summary

In the version 23.04;
the -n option is missing from the `kubectl `referenced in the  substeps mentioned in the [Step 2: Determine the original installation method](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html#step-2-determine-the-original-installation-method)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@amej Thank you for catching this! This fix will go live this week when the 23.07 changes go out.
