### ISSUE TITLE
Update the supported OpenShift versions in the requirements listed for 21.10

### ISSUE THREAD

**Issue by gnarl** [NetAppDocs/trident#33]
The supported OpenShift versions for Trident 21.10 are 4.7, 4.8, and 4.9. 

We can remove 4.4, 4.5, 4.6 (4.6.8+) from the list for with the Astra Trident and Trident operator sections. We are not claiming support for any OpenShift EUS version.

**Comment by juliantap** [comment]
Still can't add @gnarl as a reviewer, but here's the PR: https://github.com/NetAppDocs/trident/pull/34

**Comment by juliantap** [comment]
@gnarl & @balaramesh can you approve so I can push to production?

**Comment by juliantap** [comment]
@gnarl & @balaramesh can you approve so I can push to production?

**Comment by juliantap** [comment]
Thanks @gnarl @balaramesh . This has been merged to prod.
