### ISSUE TITLE
Feature requirements minimal version

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#335]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#feature-requirements

### Page title

Requirements

### Summary

Hi,

while Trident 23.07 minimal supported version of Kubernetes is 1.22, the table "Feature Requirement" still mentions 1.21 as a minimal version

++

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@YvosOnTheHub good catch! I thought I had all of them, but clearly didn't. Thanks!
