### ISSUE TITLE
Some text in wrong column

### ISSUE THREAD

**Issue by darkstar** [NetAppDocs/trident#354]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

This row in the table on the page has the `"0"` in the wrong column:
![image](https://github.com/NetAppDocs/trident/assets/43795/885808e6-5ce0-4809-a48c-da4f69d94263)
it says:
* column 2: `Percentage of volume reserved for snapshots “0”`
* column 3: `If snapshotPolicy is “none”, else “”`

The `"0"` needs to move to the right column so that it says
* column 2: `Percentage of volume reserved for snapshots`
* column 3: `"0" if snapshotPolicy is “none”, else “”`

--------

The same is true for this line:
![image](https://github.com/NetAppDocs/trident/assets/43795/db01bf03-98d4-40fb-9a5a-f9f8244c9e65)
it says:
* column 2: `Tiering policy to use “none”`
* column 3: `“snapshot-only” for pre-ONTAP 9.5 SVM-DR configuration`

it should say something like this: (if I understood it correctly)
* column 2: `Tiering policy to use`
* column 3: `"none", except for pre-ONTAP 9.5 SVM-DR configuration where it is “snapshot-only”`

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Thank you, @darkstar! This will be corrected as part of a larger pull request.
