### ISSUE TITLE
Add reference/link for:  ' Trident follows the Kubernetes optimized rolling update method' for upgrades

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#357]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator-overview.html

### Page title

Understand the operator upgrade workflow

### Summary

**Operator upgrade workflow"**
When you initiate an upgrade using the Trident operator:
--> Suggest to add wording similar to below:
  ' Trident follows the Kubernetes optimized rolling update method for upgrades'.

--> The above suggestion could also include/link to the K8S pages for rolling updates:
       https://kubernetes.io/docs/tutorials/kubernetes-basics/update/update-intro/

Justification:
We have several large customers with large node deployments and reference 'optimized rolling updates' for their upgrades.
The docs need to mention this terminology if Trident is using it.  
This will help customers and support in understanding and getting more details from the K8S pages.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Will auto-close when PR is merged.

**Comment by juliantap** [comment]
Fixed with #358
