### ISSUE TITLE
description of ontap-nas-flexgroup

### ISSUE THREAD

**Issue by netapp-dgrund** [NetAppDocs/trident#359]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas.html

### Page title

ONTAP NAS driver overview

### Summary

- You must use ontap-nas for production workloads that require data protection, disaster recovery, and mobility.
- Use ontap-san-economy when anticipated volume usage is expected to be much higher than what ONTAP supports.
- Use ontap-nas-economy only where anticipated volume usage is expected to be much higher than what ONTAP supports, and the ontap-san-economy driver cannot be used.
- Do not use use ontap-nas-economy if you anticipate the need for data protection, disaster recovery, or mobility.

Should the 3rd option not read?
- Use ontap-nas-flexgroup only where anticipated volume usage is expected to be much higher than what ONTAP supports, and the ontap-san-economy driver cannot be used.

Additionally can we eloborate a bit more on usage? Quantify  "expected to be much higher"

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Hi @netapp-dgrund, I believe it is correct as stated but I am confirming with engineering. I can also add a link to the ONTAP volume limits for general reference (though it varies by model) and am asking if we can quantify "much higher".

**Comment by netapp-dgrund** [comment]
sorry my bad, I am confused by reading this, if we are correct we want to say:
if you use ontap-nas and you run into ONTAP volume limits, you need to use ontap-nas-economy
if you use ontap-san and you run into ONTAP volume limits, you need to use ontap-san-economy
NOTE: economy driver do not do : data protection, disaster recovery, and mobility.

And we still need to add somethign about flexgroups, when do we use the flexgroup driver

On the ontap limit, we can link to the ontap limit page.
https://docs.netapp.com/us-en/ontap/volumes/storage-limits-reference.html#vollimits
