### ISSUE TITLE
Supported vs Tested Operating Systems for Trident

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#36]
Page: [Requirements](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html)

Suggest changing 'Supported host operating systems',  to  'Tested or Known working operating systems for Astra Trident'.
The wording on this page is ambiguous regarding 'Supported' Operating Systems.
This continues to cause discussion and uncertainty in many support cases, emails, chats, etc...

People (customers, TSE's, etc..) read the word 'Supported' and immediately assume we mean it the same as the Interoperability Matrix, and then do not seem to read the text underneath.

So instead of listing the OS as 'Supported',  but what we really mean is 'Tested' , .... let's just say 'Tested'.....
.............

Also, How bout adding something I saw in a recent email thread...:

"Astra Trident does not officially 'support' Trident on any specific OS, but has been tested and is known to run on the following":

..........

Just suggestions for discussion to add clarity.  Support TSE's can only go by what is shown in the docs....

Thanks!

**Comment by juliantap** [comment]
Hi @crossond -- I really like this suggestion. I'll make the change and merge it in an upcoming batch. 

As always, thank you for the feedback!

J
