### ISSUE TITLE
option listed twice

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#372]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

The limitVolumeSize option is listed twice.  Right next to itself.  Though one has extra verbiage, so I'm assuming that was supposed to replace the one instead of being added to it. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
Thanks, @NA-Scott! Fixing now!
