### ISSUE TITLE
Missing snapshotter caveat in CSI-image section

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#386]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html

### Page title

Requirements

### Summary

In all previous doc versions,  this text is included in the csi-container page:
https://docs.netapp.com/us-en/trident-2304/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions
_"On Kubernetes version 1.21 and above, use the validated registry.k8s.gcr.io/sig-storage/csi-snapshotter:v6.x image only if the v1 version is serving the volumesnapshots.snapshot.storage.k8s.gcr.io CRD. If the v1beta1 version is serving the CRD with/without the v1 version, use the validated registry.k8s.gcr.io/sig-storage/csi-snapshotter:v3.x image."_

Please check if this is still valid and add back in.
https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@crossond This was intentionally removed as obsolete in 23.07. Tagging @clintonk for awareness.

**Comment by clintonk** [comment]
@crossond  Trident 23.07 and later no longer support v1beta1 snapshots (which themselves went to v1 in K8s 1.20), so we simplified the docs accordingly.

**Comment by juliantap** [comment]
Closing after checking with requester. 

Thanks, @clintonk!
