### ISSUE TITLE
'kubectl create -f deploy/<bundle>.yaml'   is missing from Operator deployent pages

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#388]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator-mirror.html#step-4-deploy-the-trident-operator

### Page title

Manually deploy the Trident operator (Offline mode)

### Summary

The following create bundle command is missing from this procedure:

    # kubectl create -f deploy/<bundle>.yaml

It should be included in Step 4: Deploy the Trident operator
......

Steps subsection:

Steps

- Create the resources and deploy the operator:

          # kubectl kustomize deploy/ > deploy/<bundle>.yaml

-->   ** # kubectl create -f deploy/<bundle>.yaml**

Verify the operator, deployment, and replicasets were created.

           # kubectl get all -n <operator-namespace>

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
This is being fixed with #389

**Comment by juliantap** [comment]
Fixed with #396
