### ISSUE TITLE
Command should not assume post_1.25

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#390]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html

### Page title

Upgrade a Trident operator installation

### Summary

kubectl create -f 23.07.1/trident-installer/deploy/bundle_post_1_25.yaml -n trident

should be 

kubectl create -f 23.07.1/trident-installer/deploy/\<bundle-name.yaml\> -n trident

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@NA-Scott This was intended to show a specific example of how to use the bundle (per an issue opened back when we first added the `pre_` and `post_`. But I'll change it back to a variable, change the text to "where <bundle> is bundle_pre_1_25 or bundle_post_1_25 based on your Kubernetes version", and remove the explanation that it's a specific K8s 1.17 example.
