### ISSUE TITLE
Alignment is missing

### ISSUE THREAD

**Issue by jagadeeshbabuchinde** [NetAppDocs/trident#398]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html

### Page title

Prepare to configure a backend with ONTAP NAS drivers

### Summary

alignment is missing "Prepare to provision SMB volumes" in table

parameter mis aligned in example. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
@jagadeeshbabuchinde thank you for catching this! This will be resolved soon. Many thanks for contributing to the quality of our docs!

**Comment by juliantap** [comment]
@jagadeeshbabuchinde This was fixed with 23.10. Thank you again for reporting it!
