### ISSUE TITLE
Re-Add note regarding IP NATing, for Trident v23.07 and higher

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#401]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html#dynamically-manage-export-policies

### Page title

Dynamically manage export policies

### Summary

Previous versions up thru Trident v23.04 had the following note regarding NATed IPs :

https://docs.netapp.com/us-en/trident-2304/trident-use/ontap-nas-prep.html#dynamically-manage-export-policies

_"The dynamic management of export policies is only available for CSI Trident. **It is important to ensure that the worker nodes are not being NATed."_**

This note is missing in v23.07 and higher.
Has this changed?  
If no, can it be re-added to the docs?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by juliantap** [comment]
I'm going to add @clintonk to confirm this answer. 

This was intentionally removed in 23.07. There is no longer a non-CSI version of Trident and NAT capability no longer applies.

**Comment by clintonk** [comment]
> I'm adding @clintonk to confirm this answer.
> 
> This was intentionally removed in 23.07. There is no longer a non-CSI version of Trident and NAT capability no longer applies.

The NAT restriction is still relevant when using dynamic export policies.  With NAT, the storage controller sees the frontend NAT address and not the actual IP addresses of the hosts that are mounting storage volumes, so access will be denied when no match is found in the export rules.

**Comment by juliantap** [comment]
Thanks, @clintonk! I'm going to add the NAT restriction back as its own admonition. I'll also add it back to 23.07.
