### ISSUE TITLE
Trident configuration for docker, when using flexgroups, provides confusing results

### ISSUE THREAD

**Issue by adiezg** [NetAppDocs/trident#404]
### Page URL

https://docs.netapp.com/us-en/trident/trident-docker/stor-config.html

### Page title

Storage configuration options

### Summary

Hello NetApp Team

Customer has been doing some tests with flexgroups with Trident for Docker. The SVM used for the tests had two aggregates assigned
There is a recommendation in the Trident documentation to use the following: "The minimum recommended FlexGroup size is 100GB".
So based in this recommendation, the customer used the option "size" to set the default docker volume size to 100GB (as per the recommendation), in Trident backend configuration for the driver "ontap-nas-flexgroup"

**size**  Optional default size for new volumes. Default: 1G 

Then customer  created a docker volume (100G) and got the following error:
error creating FlexGroup docker_supervolume: API status: failed, Reason: Size "100GB" ("1073741824008") is too small. Minimum size is "800GB" ("858993459200B). , Code:13115

This error seems to happen, because when creating any docker volume using the ontap-nas-flexgroup driver, internally 4 ontap constituent volumes are created per aggregate (each ontap volume with 100GB size), which makes a total size of 800 GB for the docker volume (4 volumes per aggregate and the SVM has two aggregates assigned).

Customer would like the documentation to be modified, to provide additional information or warning about this behavior

Thanks in advance

TSE Alfredo Diez     

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Closed with https://github.com/NetAppDocs/trident-internal/pull/330
