### ISSUE TITLE
Link to storage class samples is incorrect

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#407]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/create-stor-class.html

### Page title

Create a storage class

### Summary

The link in the section "Storage class samples" does link to PVC examples, not storage class examples. The correct link would be https://github.com/NetApp/trident/tree/master/trident-installer/sample-input/storage-class-samples 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Updated the document to add the correct link. Worked as part of https://github.com/NetAppDocs/trident-internal/pull/330
