### ISSUE TITLE
fsType list

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#414]
### Page URL

https://docs.netapp.com/us-en/trident/trident-reference/objects.html#kubernetes-attributes

### Page title

Kubernetes and Trident objects

### Summary

The fsType list displays in the table is **"ext4, ext3, xfs, etc."**
Trident only supports "ext4, ext3, xfs", as listed on other pages.

While I understand this page is generic to Kubernetes, a note should be added to remind readers the list of supported fsTypes

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Closing this issue because the document has been updated and published.

Thanks,
Deepa
