### ISSUE TITLE
typo in command

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/trident#415]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html

### Page title

Upgrade a Trident operator installation

### Summary

wget https://github.com/NetApp/trident/releases/downloa**d/v22.01.1/**trident-installer-23.10.0.tar.gz
 should be 

wget https://github.com/NetApp/trident/releases/download**/v23.10.0/**trident-installer-23.10.0.tar.gz

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Thank you for the feedback!
The issue has been resolved and the document has been republished.

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html
