### ISSUE TITLE
ONTAP Backend config: Include local user and AD Domain user options

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#42]
Page: [Configuration options and examples](https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html)

For the ONTAP config, It would be helpful to include that it is possible to user local as well as AD Domain username.

Perhaps here:

-     "To communicate with the ONTAP cluster, you should provide the authentication parameters. This could be the 
         username/password to a security login or an installed certificate, **and can be a local or AD Domain username**."  

Please also include among the 4 listed examples for the ONTAP backend configs (NFS and iSCSI), an example syntax for 'username' for local as well as an example using the AD Domain user:

   local user:  "vsadmin" 
  
    or 
 
   Active Directory:  "username@domain"  or  "<AD domain>\\<user>"

**Comment by juliantap** [comment]
@crossond Can you give me more context on the "4 listed examples for the ONTAP config"? Are you asking for updates to the "Backend Configuration Options" table? Or for new full syntax examples? 

Also, as an update, I'm running both of these issues by engineering to make sure the AD parameters have been tested.

**Comment by gnarl** [comment]
@crossond we don't test Trident with AD and aren't currently able to support AD configuration in Trident. Currently our functional tests cover testing with certificates, cluster admin, vsadmin, etc...

AD may work but there is likely additional information for AD setup that customers would need to make such a setup work.

**Comment by juliantap** [comment]
Thanks @gnarl! 

@crossond, I will close the two issues related to AD at this time. Thank you as always for your feedback!
