### ISSUE TITLE
Trident-helm-chart github url throws 404 page not found

### ISSUE THREAD

**Issue by shazimh** [NetAppDocs/trident#420]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-helm-mirror.html

### Page title

Deploy Trident operator using Helm (Offline mode)

### Summary

In step 1 of Deploy the Trident operator and install Astra Trident using Helm, the url in the add command shows a 404 page not found. 

https://netapp.github.io/trident-helm-chart

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @shazimh, 

This is a helm repo and does not have a html page, hence when we browse it, it gives 404.
Technically, there is no issue, and it works. It's just that we can't browse it.

Please let me know if this helps.

Thanks,
Deepa
