### ISSUE TITLE
"Releases prior to 21.07" links broken

### ISSUE THREAD

**Issue by kKronstainBrown** [NetAppDocs/trident#423]
### Page URL

https://docs.netapp.com/us-en/trident/earlier-versions.html

### Page title

Earlier versions of documentation

### Summary

The two links in the Releases prior to 21.07 section are broken. Is the site down or are those versions not supported anymore. Thanks!

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
@kKronstainBrown, Thanks for reporting this. The document has been updated according to NetApp Astra Trident support lifecycle https://docs.netapp.com/us-en/trident/get-help.html. The broken links have been removed.
