### ISSUE TITLE
Removal of an instruction 

### ISSUE THREAD

**Issue by banum-netapp** [NetAppDocs/trident#429]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html

### Page title

Prepare the worker node

### Summary

Reboot your worker nodes after installing the iSCSI tools to prevent failure when attaching volumes to containers.

This statement should be removed from the documentation since it is not necessary to reboot the worker nodes after installing the iSCSI tools.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
The instruction has been removed from the document.
