### ISSUE TITLE
 Storage Config Options: Include local user and AD Domain user options

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#43]
Page: [Storage configuration options](https://docs.netapp.com/us-en/trident/trident-docker/stor-config.html)

For the ONTAP config, It would be helpful to include the examples for user local as well as AD Domain username.

Option         |     Description                                                    |   Example
username    |     Username to connect to the storage device  |   

In the Example column:

   local user:  "vsadmin" 
    or 
   Active Directory:  "username@domain"  or  "<AD domain>\\<user>"

**Comment by crossond** [comment]
Correction to above:

Option | Description | Example
username | Username to connect to the storage device | local user: "vsadmin"
                                                                                           Active Directory: "username@domain" or "<AD domain>\\<user>"

**Comment by juliantap** [comment]
Hi @crossond -- thank you for the feedback! I will add the AD example and update you when it's complete. Thanks!

**Comment by juliantap** [comment]
@crossond per @gnarl I'm closing this issue as we are unable to verify support for this AD configuration at this time. 

Thanks!

J
