### ISSUE TITLE
In the Trident Helm upgrade command Invalid version used in the --version parameter

### ISSUE THREAD

**Issue by jcurtis-netapp** [NetAppDocs/trident#431]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html#before-you-deploy

### Page title

Invalid version used in the --version parameter

### Summary

helm install <name> netapp-trident/trident-operator **--version 100.2402.0** --create-namespace --namespace <trident-namespace>

The current version number is 24.02.0. the full command would look like this
helm upgrade trident netapp-trident/trident-operator --version 24.02.0 --namespace trident

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
@jcurtis-netapp, thanks for your comment. 

The helm chart version has been updated to the format 100.2402.0 in the 24.02 release.

See https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-helm-mirror.html#critical-information-about-astra-trident-24-02.
