### ISSUE TITLE
Step 1: Select a version

### ISSUE THREAD

**Issue by jagadeeshbabuchinde** [NetAppDocs/trident#432]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-trident.html

### Page title

Upgrade Astra Trident

### Summary

Please correct the following as soon as possible with right info i updated. 22.10 is doesn't come under last four releases of 24.02.

You can perform a direct upgrade to any target release that is within a four-release window of your installed version. For example, you can directly upgrade from 23.01 (or any 23.01 dot release) to 24.02.

If you are upgrading from a release outside of the four-release window, perform a multi-step upgrade. Use the upgrade instructions for the [earlier version](https://docs.netapp.com/us-en/trident/earlier-versions.html) you are upgrading from to upgrade to the most recent release that fits the four-release window. For example, if you are running 22.01 and want to upgrade to 24.02:

First upgrade from 22.01 to 23.01.

Then upgrade from 23.01 to 24.02.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
@jagadeeshbabuchinde, thanks for reporting the issue. The document has been updated and republished.
