### ISSUE TITLE
csi-resizer version question

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#433]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html

### Page title

Requirements

### Summary

For K8s 1.27 and 1.28  the table at the bottom of the page says resizer 1.90 is the correct version, but a customer on 1.27 and my lab on 1.28 both pulled 1.93.  Is it supposed to be 1.90 or 1.93?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by NA-Scott** [comment]
Actually, it's worse that I first thought....

For K8s 1.28:

Docs:
docker.io/netapp/trident:24.02.0
docker.io/netapp/trident-autosupport:24.02
registry.k8s.io/sig-storage/csi-provisioner:v3.6.0
registry.k8s.io/sig-storage/csi-attacher:v4.4.0
registry.k8s.io/sig-storage/csi-resizer:v1.9.0
registry.k8s.io/sig-storage/csi-snapshotter:v6.3.0
registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.9.0
docker.io/netapp/trident-operator:24.02.0 (optional)

Actual:
# k describe pod/trident-controller-bfbf8d6c7-jdkv2 |grep Image
    Image:         netapp/trident:24.02.0
    Image:         docker.io/netapp/trident-autosupport:24.02
    Image:         registry.k8s.io/sig-storage/csi-provisioner:v4.0.0
    Image:         registry.k8s.io/sig-storage/csi-attacher:v4.5.0
    Image:         registry.k8s.io/sig-storage/csi-resizer:v1.9.3
    Image:         registry.k8s.io/sig-storage/csi-snapshotter:v6.3.3

There's 4 differences between docs and actual.

**Comment by NA-Scott** [comment]
The versions listed from the "tridentctl images" command match what trident uses for the install and not the documentation.

**Comment by netapp-aruldeepa** [comment]
Hi @NA-Scott, I will work with the team to make changes to the document and will share an update.

Thanks,
Deepa

**Comment by netapp-aruldeepa** [comment]
The document has been updated to correct the version numbers: https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#container-images-and-corresponding-kubernetes-versions
