### ISSUE TITLE
Upgrade a Helm installation

### ISSUE THREAD

**Issue by wbuckles-na** [NetAppDocs/trident#434]
### Page URL

https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html

### Page title

Upgrade a Trident operator installation

### Summary

In the first step in the "Upgrade a Helm installation" the version number is incorrect in the example.

Current Example:
helm upgrade trident netapp-trident/trident-operator --version 24.02.0

Corrected Example:
helm upgrade trident netapp-trident/trident-operator --version 100.2402.0

You can see the correct --version in the "Deploy the Trident operator and install Astra Trident using Helm" section, step #2 on the page pasted below.

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-helm.html#critical-information-about-astra-trident-24-02

helm install <name> netapp-trident/trident-operator --version 100.2402.0 --create-namespace --namespace <trident-namespace>

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @wbuckles-na, thanks for reporting this. We will track this internally and fix it ASAP.

**Comment by netapp-aruldeepa** [comment]
The document has been updated and published. https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html
