### ISSUE TITLE
Typo in the "ONTAP NAS driver details" table

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#439]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas.html

### Page title

ONTAP NAS driver overview

### Summary

In the table under the heading "File systems supported" the entries are "", nfs, smb.  I think the "" is a typo.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @NA-Scott, 

Thanks for your letting us know. 
I will work with my team and update the document, and let you know once done.

Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
Hi,

The double quotes ("") indicates a blank fstype. 

Astra Trident now enforces a blank `fsType` (`fsType=""`) for volumes that do not have the `fsType` specified in their StorageClass. When working with Kubernetes 1.17 or later, Trident supports providing a blank `fsType` for NFS volumes. For iSCSI volumes, you are required to set the `fsType` on your StorageClass when enforcing an `fsGroup` using a Security Context.

This is not a type; hence, closing the issue.

Thanks.
