### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/trident#441]
### Page URL

https://docs.netapp.com/us-en/trident/trident-reco/security-reco.html

### Page title

Security

### Summary

Refer to [../trident-use/ontap-san-prep.html](https://docs.netapp.com/us-en/trident/trident-use/ontap-san-prep.html) to understand how Astra Trident configures CHAP on ONTAP backends.

Link is broken and results in a 403

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @ntap-johanneswagner,

Please clear your browser cache and try to click the link.
Or try with a different browser. We could access the page in Edge without any issues, and in Crome (after clearing the browser cache).

Hope this helps.

Thanks,
