### ISSUE TITLE
update test drive references

### ISSUE THREAD

**Issue by bdeloure** [NetAppDocs/trident#442]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/intro.html

### Page title

Learn about Astra Trident

### Summary

The section with the anchor #take-the-astra-trident-test-drive  has old information.

Please coordinate with Jim Lanson.  The Astra Trident lab was pulled from Test Drive due to lack of use, and not really the scope of this service in favor of more appealing Test Drive content.  Instead of a command line focused Astra Trident lab in Test Drive, we now have an Astra Control lab that includes Astra Trident topics/discussion.  That lab is titled "Protecting Containerized Applications".

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @bdeloure,

Thanks for letting us know. We will work with Jim and update the document.

Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
Updated the latest Trident document to remove Test Drive references.
