### ISSUE TITLE
Removal of reference to Astra Trident test drive

### ISSUE THREAD

**Issue by lanson-jim** [NetAppDocs/trident#444]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/intro.html#take-the-astra-trident-test-driveml

### Page title

Take the Astra Trident test drive.

### Summary

The Astra Trident lab has been pulled from Test Drive so the paragraph referring to it should be removed.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Updated the latest Trident document to remove Test Drive references.
