### ISSUE TITLE
"kubectl install" should be "kubectl create"

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#45]
Page: [Upgrade with the operator](https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html)

The example for deploying the new operator lists the command as "kubectl install [...]":

> kubectl install -f 21.07.1/trident-installer/deploy/bundle.yaml -n trident

 That command does not exist, instead it should be "kubectl create ...".  While at it, it might make sense to update the example to the latest release as well, e.g.

> kubectl create -f 21.10.0/trident-installer/deploy/bundle.yaml -n trident

**Comment by juliantap** [comment]
Thanks, @wonderland!

@balaramesh, do you approve this requested change?

**Comment by juliantap** [comment]
@wonderland this change is being merged to prod as we speak. Thanks!
