### ISSUE TITLE
Pieces missing from the minimal configuration example

### ISSUE THREAD

**Issue by DianePatton** [NetAppDocs/trident#450]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/anf-examples.html

### Page title

Azure NetApp Files backend configuration options and examples

### Summary

The minimal configuration option seems to be missing the:
`apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-tbc-anf-1
  namespace: trident
spec:`

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @DianePatton, 

Thanks for reaching out! 

We will review the documentation and make the required changes.

Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
Hi @DianePatton,

Thank you for your feedback!

The document has been updated and republished here: https://docs.netapp.com/us-en/trident/trident-use/anf-examples.html.

Closing this issue for now. 

Regards,,
Deepa
