### ISSUE TITLE
Need documentation and usage examples for new feature listed:  limitVolumeSize parameter now limits qtree/LUN sizes in the ONTAP economy drivers. 

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#457]
### Page URL

https://docs.netapp.com/us-en/trident/trident-rn.html

### Page title

What’s new

### Summary

What'sNew page lists:

-   'IMPORTANT: The limitVolumeSize parameter now limits qtree/LUN sizes in the ONTAP economy drivers. Use the new limitVolumePoolSize parameter to control Flexvol sizes in those drivers. (Issue #341).

This parameter is not shown or explained anywhere else in the documentation, and Issue #341 still shows OPEN with no further explanation of what was added or fixed.  Last comment was on Oct 28, 2020.

Support already getting questions from customers regarding this feature.
ie.  How to change this safely after upgrade to 24.06?

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @crossond,

Thank you for bringing this up.
We will work with our team and add more information.

Thanks,
Deepa

**Comment by crossond** [comment]
Additional Comments:
Re: limitVolumeSize - considering that, since the economy volumes are generally much larger, it won't affect the PV creation anyway. However, without adding the new limitation parameter in the backend under 24.06.0, the main volume will now grow without bounds...
 
Need documentation to understand how to configure or re-configure limitVolumeSize and how to use limitVolumePoolSize starting in v24.06+

**Comment by crossond** [comment]
any update on this?  Have a customer upgrading large prod deployment today using ontap-san-economy and is asking
Can we please get a response ASAP?

**Comment by netapp-aruldeepa** [comment]
Trident document has been updated with 'limitVolumePoolSize' information.  This page and other relevant pages have been updated: https://docs.netapp.com/us-en/trident/trident-docker/stor-config.html and
