### ISSUE TITLE
StoragePrefix needs a new note

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#463]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

We need a new note in the storagePrefix option with text similar to:
Note: When using ontap-nas-economy and a storagePrefix that is 24 or more characters, the qtrees will not have the storage prefix embedded, though it will be in the volume name.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @NA-Scott,

Thank you for your feedback!

We'll work with the team and update the document.

Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
The document has been updated to resolve this issue:  https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html
