### ISSUE TITLE
New 'limitvolumepoolsize' parameter is missing from the list of parameters

### ISSUE THREAD

**Issue by shazimh** [NetAppDocs/trident#474]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

In this 24.06 version of trident the newly introduced parameter 'limitVolumePoolSize' isn't listed in the documentation and needs to be added.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @shazimh, 

Thank you for your feedback.
We are working with our team to update the document with the 'limitVolumePoolSize' parameter.
We will keep you posted.


Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
Closing this issue. The 'limitVolumePoolSize' parameter has been updated on this page: https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html and on other pages as required.
