### ISSUE TITLE
Change order of installation steps

### ISSUE THREAD

**Issue by Wagz123** [NetAppDocs/trident#476]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/quickstart.html

### Page title

Quick start for Astra Trident

### Summary

Prepare worker node should be step 1 before trident installation. NVME nqn and ISCSI iqn need to be present during installation so that Trident can read them at install time. Failure to do so requires customers to restart trident later on which is not intuitive.  In the case of NVME, nqn is not re-read after install even  if restarting trident. That might be a bug, but simply placing the worker preparation before trident installation solves all problems.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
The document has been updated to rearrange the installation steps.
