### ISSUE TITLE
Remove mention of Kubernetes cluster management from BlueXP

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/trident#477]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy.html

### Page title

Learn about Astra Trident installation

### Summary

We need to remove the following section from the documentation. This ability has been removed from BlueXP.

> Kubernetes cluster management using BlueXP (formerly Cloud Manager)
> 
> With [Astra Trident using BlueXP](https://docs.netapp.com/us-en/cloud-manager-kubernetes/concept-kubernetes.html), you can upgrade to the latest version of Astra Trident, add and manage storage classes and connect them to Working Environments, and back up persistent volumes using Cloud Backup Service. BlueXP supports Astra Trident deployment using the Trident operator, either manually or using Helm.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi Ben @netapp-bcammett,

Thanks for your letting us know.

We will update the document and keep you posted,

thanks,
Deepa
