### ISSUE TITLE
Is Rancher RKE2 supported, or just RKE1?

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#480]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html

### Page title

Requirements

### Summary

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#supported-frontends-orchestrators

It lists "Rancher", but Rancher RKE1 and RKE2 are fairly different.  I think I recall seeing where Trident doesn't play well with RKE2.  If my memory is correct and we don't then we should specify 'Rancher RKE1' in the docs instead of just 'Rancher'.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @NA-Scott,

Thank you for your feedback.
We will work with our team and update the documentation as required.

Thanks,
Deepa

**Comment by netapp-aruldeepa** [comment]
Hi @NA-Scott,

We have updated the document to mention support for RKE2.

Thanks,
Deepa
