### ISSUE TITLE
DataLIF type

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#486]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-san-examples.html

### Page title

ONTAP SAN configuration options and examples

### Summary

Hi,

with **ONTAP-NAS**, you can optionally set the DataLIF parameter. There is also some information about the IPv6 support for that parameter.

With **ONTAP-SAN**, it is recommended not to set that parameter for iSCSI (because it would break multipathing).
Howerer, we do not explicitly say that the LIF in ONTAP can be configured with IPv6

could that information be added?

thanks

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @YvosOnTheHub, 

Thanks for sharing the information. I will work with my team and update the documentation.

Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
The document has been updated to include IPv6 information in ONTAP-NAS, similar to ONTAP-SAN.
