### ISSUE TITLE
denyNewVolumePools is missing

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/trident#490]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

Release Notes: "Added denyNewVolumePools configuration parameter to restrict ONTAP-NAS-Economy and ONTAP-SAN-Economy drivers to preexisting Flexvol pools."
This is reflected in the docs for SAN but not for NAS. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @ntap-johanneswagner,

Thanks, for sharing the details!

We have updated the page with the required information: https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html#backend-configuration-options-for-provisioning-volumes 

Regards,
Deepa
