### ISSUE TITLE
lunsPerFlexvol should not be present

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#493]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

the _lunsPerFlexvol_ parameter is only usable with SAN drivers, however it is listed as an option for the NAS drivers
it should be removed

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
The document has been updated to remove 'lunsPerFlexvol' from the page.

Thanks,
Deepa
