### ISSUE TITLE
denyNewVolumePools parameter in the wrong table

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#494]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-examples.html

### Page title

ONTAP NAS configuration options and examples

### Summary

the _denyNewVolumePools_ parameter should be displayed in the first table (which starts with _version_), and not the second one (which start with _spaceAllocation_)

same thing for the ONTAP-SAN page

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
The document has been updated.

Thanks,
Deepa
