### ISSUE TITLE
Extra character in Ubuntu iSCSI setup instructions

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#496]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/worker-node-prep.html

### Page title

Prepare the worker node

### Summary

The section "Install the iSCSI tools" contains the tab for Ubuntu instructions. In this, step 4 ("Enable multipathing") has an extra character that breaks the command. 

The first line currently is

`sudo tee /etc/multipath.conf <<-'EOF`

The ' in front of EOF does not belong there and needs to be removed (possibly a byproduct of formatting instructions?). The correct line would be

`sudo tee /etc/multipath.conf <<-EOF`

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
The document has been updated to remove the extra character. 
Thanks,
Deepa
