### ISSUE TITLE
Helm Repo link faulty

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#500]
### Page URL

https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-installation.html

### Page title

Install and configure Trident protect

### Summary

the current path for the helm chart is:
_helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart/index.yaml_
whereas is should be
_helm repo add netapp-trident-protect https://netapp.github.io/trident-protect-helm-chart_

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @YvosOnTheHub, thanks for opening this issue.  We're looking in to this right now, and will update with a fix shortly.
Thanks,
Michael
