### ISSUE TITLE
Command to create completion folder faulty

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#501]
### Page URL

https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-cli.html

### Page title

Install the Trident protect CLI plugin

### Summary

documentation displays: 
_md ~/.bash/completions_
I believe it should be 
_mkdir -p ~/.bash/completions_

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @YvosOnTheHub. thanks for opening this issue. I'll have this fixed in the docs today.
