### ISSUE TITLE
Image netapp/resourcedelete:24.10.0 missing from the list of requirements

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetAppDocs/trident#502]
### Page URL

https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-installation.html

### Page title

Install and configure Trident protect

### Summary

when setting up Trident Protect with a private registry, the list of images is incomplete
netapp/resourcedelete:24.10.0 is missing

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-mwallis** [comment]
Hi @YvosOnTheHub, thanks for alerting us to this issue. I'm checking on this with engineering, and will respond shortly with a resolution.
Thanks,
Michael
