### ISSUE TITLE
Replace CVS with Google Cloud NetApp Volumes

### ISSUE THREAD

**Issue by deansteadman** [NetAppDocs/trident#505]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html

### Page title

Requirements

### Summary

Please replace Cloud Volume Service for GCP with Google Cloud NetApp Volumes in the storage backend section

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
@deansteadman,

We have updated the storage backend section.

https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html

Thanks,
Deepa
