### ISSUE TITLE
Replace CVS with Google Cloud NetApp Volumes 

### ISSUE THREAD

**Issue by deansteadman** [NetAppDocs/trident#506]
### Page URL

https://docs.netapp.com/us-en/trident/trident-get-started/intro.html

### Page title

Learn about Trident

### Summary

Please remove CVS and add Google Cloud NetApp Volumes with this description. 

Google Cloud NetApp Volumes, a fully managed file storage service in Google Cloud that provides high-performance, enterprise-grade file storage. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @deansteadman,

We have updated the document to replace CVS with GCNV.

https://docs.netapp.com/us-en/trident/trident-get-started/intro.html 

Thanks,
Deepa
