### ISSUE TITLE
Update for 24.10 release 

### ISSUE THREAD

**Issue by deansteadman** [NetAppDocs/trident#508]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/gcnv.html

### Page title

Configure a Google Cloud NetApp Volumes backend

### Summary

24.10 makes this feature set GA. Please remove the tech preview note.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @deansteadman,

Thanks for sharing this. We have updated the document.

https://docs.netapp.com/us-en/trident/trident-use/gcnv.html 

-Deepa
