### ISSUE TITLE
List Google Cloud NetApp Volumes backend

### ISSUE THREAD

**Issue by okrause** [NetAppDocs/trident#528]
### Page URL

https://docs.netapp.com/us-en/trident/trident-use/backends.html

### Page title

Configure backends

### Summary

GCNV is missing from the overview page.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-aruldeepa** [comment]
Hi @okrause,

Thanks for sharing this.
We will update the page to include DCNV information.

Regards,
Deepa

**Comment by netapp-aruldeepa** [comment]
The document has been updated to list GCNV on the Backends page.
