### ISSUE TITLE
According to release notes the latest K8s version is wrong.

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#62]
Page: [Requirements](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html)

According to the release notes:
Kubernetes: Added support for Kubernetes 1.23.

But the requirements page still lists 1.22

**Comment by NA-Scott** [comment]
https://github.com/NetApp/trident/releases/tag/v22.01.0

**Comment by juliantap** [comment]
@balaramesh & @gnarl I think we need to update the Kubernetes & container image versions in https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html.

**Comment by gnarl** [comment]
Hi @juliantap, I'll get a PR to you this morning and I'll take the AI for getting this gap closed.

**Comment by juliantap** [comment]
Thanks @NA-Scott! This is merging into production as we speak (<30 minutes).
