### ISSUE TITLE
Specify the command for which the command line options are used; with examples 

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#66]
Page: [Command-line options](https://docs.netapp.com/us-en/trident/trident-reference/trident-cl.html)

Specify the command which the command line options are used; with examples 

This page shows the command line options,  **but for which command ?**
# tridentctl ?
# kubectl ?

**- Note: The options listed on this page are not shown in the --help option output for either command above.**

**- It would be very helpful to include a few examples showing use and syntax.**

**Comment by juliantap** [comment]
Thanks, @crossond! I'll work with eng and reply back when I've got information.

**Comment by crossond** [comment]
Thank you!

**Comment by juliantap** [comment]
@crossond I'm working with @reederc42 on this issue. His response is as follows:

Those options are for the orchestrator, not tridentctl or kubectl; it's the binary that runs inside the k8s pod or docker plugin. They are relevant only when modifying a deployment, for example with custom yaml option on tridentctl.

kubctl documentation is robust, so we don't want to duplicate it. But we will make it clear that these are for orchestrator (not tridentctl). 

I'll leave this open until I update the docs with the clarification. 

Thanks!

J

**Comment by juliantap** [comment]
@crossond I've added clarification to the page. Let me know it doesn't resolve the issue. Thanks, as always, for your feedback!
