### ISSUE TITLE
Add allowVolumeExpansion to storage class documentation

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#76]
Page: [Kubernetes and Trident objects](https://docs.netapp.com/us-en/trident/trident-reference/objects.html)

https://docs.netapp.com/us-en/trident/trident-reference/objects.html#kubernetes-attributes

Can we please add  allowVolumeExpansion to the list of Kubernetes attributes? This has been part of CSI since K8s 1.16 and I'd consider it a best practise to add this to storage class definitions.

| Attribute  | Type | Values | Description | Relevant Drivers | Kubernetes Version
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| allowVolumeExpansion  | boolean | true, false |  Enable or disable support for growing the PVC size | ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, aws-cvs, gcp-cvs, azure-netapp-files | 1.16+

Please see https://docs.netapp.com/us-en/trident/trident-use/vol-expansion.html for further details on volume expansion.

Also, can we please add this attribute to the example YAML manifest for a storage class shown on this page?

**Comment by juliantap** [comment]
@balaramesh can you provide approval for this addition & an updated YAML example that includes `allowVolumeExpansion`?

**Comment by balaramesh** [comment]
@juliantap I approve. I think we should also add another column for volumeBindingMode, since that is also another parameter Trident supports.

The YAML example will look like this:
```
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: <Name>
provisioner: csi.trident.netapp.io
mountOptions: <Mount Options>
parameters:
  <Trident Parameters>
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

**Comment by balaramesh** [comment]
The entry for volumeBindingMode should look like this IMO:
| Attribute  | Type | Values | Description | Relevant Drivers | Kubernetes Version
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| volumeBindingMode | string | Immediate, WaitForFirstConsumer |  Choose when volume binding and dynamic provisioning occurs | ontap-nas, ontap-nas-economy, ontap-nas-flexgroup, ontap-san, solidfire-san, aws-cvs, gcp-cvs, azure-netapp-files | 1.16+
