### ISSUE TITLE
Add note that NAE is not supported in Trident

### ISSUE THREAD

**Issue by crossond** [NetAppDocs/trident#83]
Page: [Driver-specific volume options](https://docs.netapp.com/us-en/trident/trident-docker/volume-driver-options.html)

On this page, in the table for ONTAP Volume Options, for 'encryption' , Add a note specific to NAE, as suggested below:

encryption  |  This will enable NetApp Volume Encryption (NVE) on the new volume, defaults to false. NVE must be licensed and enabled on the cluster to use this option.  **NetApp Aggregate Encryption (NAE) is not currently supported in Trident.**

.................

Justification:

Support has had several (at least 3) support cases where customers have enabled NAE which breaks their ability to create volumes in those aggregates.  It would be helpful to specifically state NAE is not supported in Trident at this time.  
Once NAE is supported, the documentation can then be updated for versions going forward. 

One recent customer comment is below which demonstrates the confusion and why NAE is assumed to not be something that will impact Trident,  until customer has already enabled it due to it is assumed NAE covers NVE volumes. 

Customer comment:
_“I still don't understand why Trident (a front-end tool) even cares whether the backend is encrypted and whether it's NVE or NAE.  
Trident is just telling the storage to create the volume.  I get that a NAE aggregate will create a NAE volume, but why does Trident care?  I will say that I'm disappointed and don't understand why Trident only supports NVE or plain-text volumes.  That is ridiculous.  
Resolving this should not be an enhancement request but a requirement as this is a gap.”_
........................

Note: There is an open enhancement issue for NAE support here:   https://github.com/NetApp/trident/issues/672.

This doc change will help customers and support clearly understand that NAE is not supported currently, since more than 1 customer has made the wrong assumption and implemented NAE, only to find that it broke Trident.

**Comment by gnarl** [comment]
@juliantap, this looks accurate to me.

**Comment by juliantap** [comment]
This issue will be resolved and closed with https://github.com/NetAppDocs/trident-internal/pull/42.

Thanks again, @crossond!
