### ISSUE TITLE
Small typo limitVolumeSizee

### ISSUE THREAD

**Issue by wonderland** [NetAppDocs/trident#86]
Page: [Storage configuration options](https://docs.netapp.com/us-en/trident/trident-docker/stor-config.html)

The table for the Ontap configuration options contains a small typo, there is an extra "e" in limitVolumeSizee It should be limitVolumeSize (same is in the table with the global options).

**Comment by juliantap** [comment]
Ah, good catch @wonderland! Thanks for letting me know. I'll get this fixed.

**Comment by juliantap** [comment]
Hi @wonderland, this issue has now been merged. Thank you for alerting me! ~ Julia
