### ISSUE TITLE
AWS - Regions, AZs and Nodes

### ISSUE THREAD

**Issue by wbuckles** [NetAppDocs/trident#92]
Page: [Use CSI Topology](https://docs.netapp.com/us-en/trident/trident-use/csi-topology.html)

Currently:
"Nodes can be located in different regions within an availability zone, or across various availability zones. "

Proposed change:

"Nodes can be located in different availability zones within a region, or across various regions. "

*****************************************************************************************************************

In AWS, regions are geographic locations that are made up of two ore more availability zones.
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html

There are also examples further down the page in the that support the AWS architecture.

{"version": 1,
"storageDriverName": "ontap-nas",
"backendName": "nas-backend-us-central1",
"managementLIF": "172.16.238.5",
"svm": "nfs_svm",
"username": "admin",
"password": "Netapp123",
"supportedTopologies": [
      {"topology.kubernetes.io/region": "us-central1", "topology.kubernetes.io/zone": "us-central1-a"},
      {"topology.kubernetes.io/region": "us-central1", "topology.kubernetes.io/zone": "us-central1-b"}
    ]
"storage": [
   {
       "labels": {"workload":"production"},
        "region": "Iowa-DC",
        "zone": "Iowa-DC-A",
        "supportedTopologies": [
            {"topology.kubernetes.io/region": "us-central1", "topology.kubernetes.io/zone": "us-central1-a"}
        ]
    },
    {
        "labels": {"workload":"dev"},
         "region": "Iowa-DC",
         "zone": "Iowa-DC-B",
         "supportedTopologies": [
             {"topology.kubernetes.io/region": "us-central1", "topology.kubernetes.io/zone": "us-central1-b"}
         ]
     }
]
}

**Comment by juliantap** [comment]
Hi @wbuckles -- good to "see" you! Thanks for the feedback!

@reederc42, do you approve the proposed change?

**Currently:
"Nodes can be located in different regions within an availability zone, or across various availability zones. "

Proposed change:

"Nodes can be located in different availability zones within a region, or across various regions. "**

**Comment by reederc42** [comment]
Yes, that looks good to me, @juliantap

**Comment by juliantap** [comment]
> Yes, that looks good to me, @juliantap

Thanks, @reederc42! I'll make this change.

**Comment by juliantap** [comment]
@wbuckles, this issue is now resolved. Thanks again for the feedback!
