### ISSUE TITLE
UseCHAP set to "nfsvers=3"... really?

### ISSUE THREAD

**Issue by NA-Scott** [NetAppDocs/trident#95]
Page: [Configure a NetApp HCI or SolidFire backend](https://docs.netapp.com/us-en/trident/trident-use/element.html)

UseCHAP | Use CHAP to authenticate iSCSI | "nfsvers=3"

Ummm... what?

**Comment by NA-Scott** [comment]
UseCHAP should be a true/false and it definitely doesn't have anything to do with nfs.  At least one item in this table is wrong.  I'm not sure about the rest of it.  Someone needs to look at the whole table and check it.

**Comment by juliantap** [comment]
@balaramesh Can you assist with this? Who can review the SF backend config options?

**Comment by juliantap** [comment]
Fixed with #102 

Thanks, @balaramesh  & @NA-Scott!
